import React,{useLayoutEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {useCollection} from '../src/hooks/useCollection';
import CaptainsManager from '../src/views/dashboard/CaptainsManager';
import Operations from './Operations';
import clubStyles from '../src/index.css?inline';
const accountTheme=`:host{display:block;color:#25364a;font-family:Tahoma,Arial,sans-serif}.bg-slate-950,.bg-slate-900,.bg-slate-800{background:#fff!important}.text-slate-100,.text-slate-200,.text-white{color:#182b42!important}.text-slate-300,.text-slate-400,.text-slate-500{color:#56677b!important}.border-slate-700,.border-slate-800{border-color:#dfe6ed!important}.text-yellow-500,.text-yellow-400{color:#947123!important}.bg-yellow-500{background:#dec285!important;color:#192a42!important}input,select{background:#f8fafc!important;color:#182b42!important;border-color:#cdd7e2!important}.shadow-lg,.shadow-xl{box-shadow:none!important}h2,h3{color:#192a42!important}`;
export default function ClubPages({page,branch,user,demo=false}){return page==='captains'?<Accounts user={user} demo={demo}/>:<Operations key={page+branch} page={page} branch={branch} demo={demo}/>;}
function Accounts({user,demo}){const captains=useCollection('captains',{enabled:!demo&&user.isSuper===true});if(demo)return <section className="panel"><h2>حسابات تطبيق النادي</h2><p>إنشاء حسابات الدخول وتعديل صلاحياتها متاح في الجلسة الفعلية للمدير. لا تُنشأ حسابات حقيقية من المعاينة التجريبية.</p><p className="badge">مدرب تجريبي · شفا بدران · الطلاب والحضور</p></section>;if(!user.isSuper)return <p className="error">هذا القسم متاح للمدير العام فقط.</p>;if(captains.error)return <p className="error">تعذر تحميل الحسابات.</p>;if(captains.loading)return <p className="notice">جارٍ تحميل الحسابات…</p>;return <section className="panel"><p>حساب الدخول وصلاحيات تطبيق النادي. الراتب والحضور الإداري لهما ملف منفصل ضمن «فريق التدريب».</p><AccountShell><CaptainsManager captains={captains.data} captainsCollection={captains}/></AccountShell></section>;}
function AccountShell({children}){const host=useRef(null),[root,setRoot]=useState(null);useLayoutEffect(()=>{setRoot(host.current.shadowRoot||host.current.attachShadow({mode:'open'}));},[]);return <div ref={host}>{root&&createPortal(<><style>{clubStyles}{accountTheme}</style>{children}</>,root)}</div>;}
