import Overview from './Overview';
import AccessPanel from './AccessPanel';
import {Sidebar,SectionTabs,ADMIN_AREAS,PAGE_HELP} from './Navigation';
import ClubPages from './ClubPages';
import {isManagementClubPage} from '../src/lib/portalPages';
import {downloadDatabaseBackup} from '../src/lib/databaseBackup';
import React,{useEffect,useState,useRef} from 'react';

import {collection,doc,onSnapshot,setDoc,runTransaction,query,where} from 'firebase/firestore';
import {db} from '../src/lib/firebase';
const path=['artifacts','brave-academy-live-data','public','data'];
import {payroll,totals,dayString,money} from './domain.mjs';

const currentMonth=`${new Date().getFullYear()}-${String(new Date().getMonth()+1).padStart(2,'0')}`;
const sections=Object.fromEntries(ADMIN_AREAS.flatMap(a=>a.items.map(([key,label])=>[key,label])));
const fmt=n=>Number(n||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const legacy=['students','payments','expenses','income_extra','debts'];
const fresh=['management_coaches','management_months','management_ledger','management_notes','management_users'];
const demo=import.meta.env.DEV && new URLSearchParams(location.search).get('demo')==='1';
const demoData={students:[{id:'s1',name:'طالب تجريبي',branch:'شفا بدران',subEnd:'2099-01-01'}],payments:[{id:'p1',studentName:'طالب تجريبي',amount:520,date:currentMonth+'-01',branch:'شفا بدران'}],expenses:[{id:'e1',title:'إيجار تجريبي',amount:150,date:currentMonth+'-01',branch:'شفا بدران'}],income_extra:[],debts:[],management_coaches:[{id:'c1',name:'مدرب تجريبي',salary:520,branch:'شفا بدران'}],management_months:[{id:'c1_'+currentMonth,coachId:'c1',month:currentMonth,salary:520,paid:0,attendance:{[currentMonth+'-01']:true,[currentMonth+'-02']:true},branch:'شفا بدران'}],management_ledger:[],management_notes:[],management_users:[]};
export default function ManagementPortal({account,onLogout}){
 const user=account;
 const [theme,setTheme]=useState(()=>{try{return localStorage.getItem('brave-management-theme')==='dark'?'dark':'light';}catch{return 'light';}});
 const toggleTheme=()=>setTheme(v=>{const next=v==='dark'?'light':'dark';try{localStorage.setItem('brave-management-theme',next);}catch{}return next;});
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[data,setData]=useState(demo?demoData:{}),[loads,setLoads]=useState({}),[tab,setTab]=useState('overview'),[month,setMonth]=useState(currentMonth),[branch,setBranch]=useState('all'),[coachId,setCoachId]=useState(''),[detail,setDetail]=useState(null);
 const allowed=key=>user?.isSuper===true || (!['captains','backup','access'].includes(key)&&(user?.permissions?.includes(key)||(key==='finance'&&user?.permissions?.includes('accounts'))));
 const permissionKey=JSON.stringify(user);
 useEffect(()=>{if(!user||demo)return;const available=[...(allowed('overview')||user?.permissions?.includes('finance')?legacy:allowed('reports')?['students','payments','expenses','income_extra']:allowed('finance')?['payments','expenses','income_extra']:[]),...(allowed('coaches')||allowed('attendance')||allowed('payroll')||allowed('notes')?['management_coaches']:[]),...(allowed('attendance')||allowed('payroll')||allowed('overview')?['management_months']:[]),...(allowed('finance')||allowed('reports')||allowed('payroll')||allowed('overview')?['management_ledger']:[]),...(allowed('notes')?['management_notes']:[]),...(user.isSuper?['management_users']:[])];setLoads(Object.fromEntries(available.map(n=>[n,'loading'])));return (()=>{const stops=available.map(name=>onSnapshot(name==='management_ledger'&&!allowed('finance')&&!allowed('overview')&&!allowed('reports')?query(collection(db,...path,name),where('kind','in',['salary','advance'])):collection(db,...path,name),snapshot=>{setData(old=>({...old,[name]:snapshot.docs.map(d=>({...d.data(),id:d.id}))}));setLoads(old=>({...old,[name]:'ready'}));},()=>setLoads(old=>({...old,[name]:'error'}))));return ()=>stops.forEach(stop=>stop());})();},[permissionKey]);
 useEffect(()=>{if(user&&!allowed(tab)){setTab(Object.keys(sections).find(key=>key!=='access'&&allowed(key))||'none');}},[permissionKey,tab]);
 const actionGuard=useRef(false);
 const act=async fn=>{if(actionGuard.current)return;actionGuard.current=true;setBusy(true);setError('');try{await fn();}catch(e){setError(e.message||'تعذر الحفظ. حاول مرة أخرى.');}finally{actionGuard.current=false;setBusy(false);}};
 const save=async(name,id,record)=>{if(!fresh.includes(name))throw Error('الكتابة على بيانات النظام الحالي غير مسموحة.');if(demo){setData(old=>({...old,[name]:[...(old[name]||[]).filter(r=>r.id!==id),{...record,id}]}));return;}await setDoc(doc(db,...path,name,id),record);};
 const coaches=(data.management_coaches||[]).filter(c=>branch==='all'||c.branch===branch),coach=coaches.find(c=>c.id===coachId),record=(data.management_months||[]).find(r=>r.coachId===coachId&&r.month===month),summary=totals(data,month,branch);
 const mutateMonth=async change=>{const id=coachId+'_'+month;if(demo){const latest=(data.management_months||[]).find(r=>r.id===id);await save('management_months',id,change(latest));return;}await runTransaction(db,async tx=>{const ref=doc(db,...path,'management_months',id),snapshot=await tx.get(ref);tx.set(ref,change(snapshot.exists()?snapshot.data():null));});};
 const formData=e=>{e.preventDefault();return Object.fromEntries(new FormData(e.currentTarget));};
 const addPayment=async values=>{const id=crypto.randomUUID();const amount=money(values.amount);if(amount<=0)throw Error('أدخل مبلغاً موجباً.');const entry={kind:values.kind==='advance'?'advance':'salary',coachId,month,amount,date:values.date,branch:coach.branch,title:`${values.kind==='advance'?'سلفة':'راتب'} ${coach.name} — ${month}`,createdBy:user.email};if(demo){if(!record||amount>payroll(record).remaining)throw Error('المبلغ يتجاوز المتبقي المستحق.');await save('management_months',record.id,{...record,paid:money(Number(record.paid||0)+amount)});await save('management_ledger',id,entry);return;}await runTransaction(db,async tx=>{const ref=doc(db,...path,'management_months',record.id),snap=await tx.get(ref);if(!snap.exists()||amount>payroll(snap.data()).remaining)throw Error('المبلغ يتجاوز المتبقي المستحق.');tx.update(ref,{paid:money(Number(snap.data().paid||0)+amount),lastPayment:id});tx.set(doc(db,...path,'management_ledger',id),entry);});};
 const sourceNames={students:'الطلاب',payments:'الوصولات',expenses:'المصروفات',income_extra:'الدخل الإضافي',debts:'الذمم',management_coaches:'المدربون',management_months:'الحضور والرواتب',management_ledger:'الحركة المالية',management_notes:'الملاحظات',management_users:'الصلاحيات'};
 const pending=Object.values(loads).some(v=>v==='loading'),failed=Object.entries(loads).filter(([,v])=>v==='error');
 const navigate=key=>{setTab(key);setDetail(null);setError('');};
 const scopedLedger=[...summary.receipts.map(r=>({...r,title:r.studentName||r.sid||'وصل طالب',kind:'income',source:'وصولات الطلاب'})),...summary.extra.map(r=>({...r,kind:'income',source:'دخل إضافي'})),...summary.expenses.map(r=>({...r,kind:'expense',source:'مصروفات النادي'})),...summary.ledger.map(r=>({...r,source:r.kind==='salary'||r.kind==='advance'?'رواتب وسلف':'حركة إدارية'}))].sort((a,b)=>dayString(b.date).localeCompare(dayString(a.date)));
 return <div className="layout" dir="rtl" data-theme={theme}><Sidebar tab={tab} allowed={allowed} onNavigate={navigate} user={user} onLogout={onLogout}/><main><header className="page-header"><div><div className="eyebrow">اكاديمية الشجاع / الإدارة العامة</div><h1>{sections[tab]||'لا توجد صلاحيات مفعلة'}</h1><p>{PAGE_HELP[tab]}</p></div><div className="filters"><button className="theme-toggle quiet" aria-pressed={theme==='dark'} onClick={toggleTheme}>{theme==='dark'?'☀ الوضع الفاتح':'☾ الوضع الداكن'}</button>{['overview','finance','reports','attendance','payroll'].includes(tab)&&<label>الفترة المالية<input lang="en" type="month" value={month} onChange={e=>{if(e.target.value){setMonth(e.target.value);setDetail(null);}}} required/></label>}<label>نطاق العرض<select value={branch} onChange={e=>{setBranch(e.target.value);setCoachId('');setDetail(null);}}><option value="all">جميع الفروع</option><option>شفا بدران</option><option>أبو نصير</option></select></label></div></header><SectionTabs tab={tab} allowed={allowed} onNavigate={navigate}/>{demo&&<p className="notice">معاينة ببيانات تجريبية — لا تقرأ أو تعدّل بيانات النادي</p>}{error&&<p role="alert" className="error">{error}</p>}{pending&&<p className="notice">جارٍ تحميل السجلات…</p>}{failed.length>0&&<p role="alert" className="error">تعذر تحميل: {failed.map(([n])=>sourceNames[n]||n).join('، ')}. الملخصات غير مكتملة؛ لا تعتمد أرقامها حتى يتصل المصدر.</p>}
 {tab==='overview'&&!pending&&!failed.length&&<Overview summary={summary} data={data} month={month} branch={branch} ledger={scopedLedger} onDetails={setDetail} onNavigate={navigate} allowed={allowed}/>}
 {isManagementClubPage(tab)&&!['accounts','reports'].includes(tab)&&allowed(tab)&&<ClubPages key={tab+branch} page={tab} branch={branch} user={user} demo={demo} theme={theme}/>}
 {tab==='backup'&&user.isSuper&&<section className="panel"><h2>نسخة بيانات جميع الفروع</h2><p>تُقرأ السجلات مباشرة من قاعدة البيانات، وتشمل الطلاب والمالية والمخزون وحضور المدربين ورواتبهم والسلف والصلاحيات. يتوقف التنزيل إذا تعذر تحميل أي مجموعة.</p><p>هذا الملف لا يشمل ملفات الصور والمرفقات ولا حسابات Firebase Authentication؛ تحتاج نسخة خادم منفصلة للاستعادة الكاملة.</p><button disabled={busy} onClick={()=>act(async()=>{if(demo)throw Error('النسخ الاحتياطي غير متاح في العرض التجريبي.');await downloadDatabaseBackup();})}>{busy?'جارٍ إعداد النسخة…':'تحميل النسخة الاحتياطية'}</button></section>}
 {detail&&<section className="panel"><button className="quiet" onClick={()=>setDetail(null)}>إغلاق التفاصيل ×</button><h2>{detail.label}</h2>{detail.type==='students'||detail.rows.some(r=>r.subEnd||r.joinDate)?<StudentRows rows={detail.rows}/>:<Rows rows={detail.rows}/>}</section>}
 {['finance','reports'].includes(tab)&&!pending&&!failed.length&&<>
 <section className="cards financial-cards">{[['الدخل المحصّل',summary.income,'income'],['المصروفات المدفوعة',summary.outgoing,'expense'],['صافي الحركة',summary.net,'net']].map(([label,value,tone])=><div className={'metric '+tone} key={label}><span>{label}</span><strong>{fmt(value)} <small>د.أ</small></strong><small>{month} · {branch==='all'?'جميع الفروع':branch}</small></div>)}</section>
 {tab==='finance'&&<details className="panel action-panel"><summary>＋ تسجيل حركة مالية جديدة</summary><form className="inline" onSubmit={e=>{const v=formData(e),form=e.currentTarget;act(async()=>{const row={...v,amount:money(v.amount),createdBy:user.email};if(demo||user.isSuper||user.permissions?.includes('finance'))await save('management_ledger',crypto.randomUUID(),row);else {const name=v.kind==='income'?'income_extra':'expenses';await setDoc(doc(db,...path,name,crypto.randomUUID()),row);}form.reset();});}}><label>نوع الحركة<select name="kind"><option value="income">دخل إضافي</option><option value="expense">مصروف</option></select></label><label>البيان<input name="title" required maxLength={200}/></label><label>المبلغ (د.أ)<input name="amount" type="number" min="0.01" step="0.01" required/></label><label>التاريخ<input name="date" lang="en" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></label><BranchField/><button disabled={busy}>حفظ الحركة</button></form></details>}
 <section className="panel"><div className="panel-heading"><div><h2>{tab==='reports'?'كشف الحركة المالية':'سجل مالي موحّد'}</h2><p>وصولات الطلاب والدخل والمصروفات ودفعات الرواتب؛ كل حركة محسوبة مرة واحدة.</p></div><button className="quiet" onClick={()=>window.print()}>طباعة الكشف</button></div><Rows rows={scopedLedger}/></section>
 {tab==='reports'&&<section className="panel"><h2>كشف الطلاب الحاليين</h2><p>حالة الطلاب الحالية في الفرع المحدد، مستقلة عن شهر الحركة المالية.</p><StudentRows rows={summary.students}/></section>}
 </>}
 {tab==='coaches'&&<><section className="panel"><h2>دليل فريق التدريب</h2><div className="coach-grid">{coaches.map(c=><article className="coach-card" key={c.id}><div className="avatar">{c.name?.slice(0,1)}</div><h3>{c.name}</h3><span className="badge">{c.branch}</span><p>الراتب المرجعي <strong>{fmt(c.salary)} د.أ</strong></p><div className="coach-actions">{[['attendance','الحضور'],['payroll','الراتب'],['notes','الملاحظات']].filter(([key])=>allowed(key)).map(([key,label])=><button className="quiet" key={key} onClick={()=>{setCoachId(c.id);navigate(key);}}>{label}</button>)}</div><details><summary>تعديل الملف والراتب القادم</summary><form onSubmit={e=>{const v=formData(e);act(()=>save('management_coaches',c.id,{name:v.name,branch:c.branch,salary:money(v.salary)}));}}><label>الاسم<input name="name" required defaultValue={c.name}/></label><label>راتب الشهور القادمة<input name="salary" type="number" min="0" step="0.01" required defaultValue={c.salary}/></label><small>رواتب الشهور المعتمدة تبقى كما هي.</small><button disabled={busy}>حفظ التعديل</button></form></details></article>)}</div>{!coaches.length&&<p className="empty">لا يوجد مدربون في هذا الفرع. أضف ملف المدرب للبدء.</p>}</section><form className="panel inline" onSubmit={e=>{const v=formData(e),form=e.currentTarget;act(async()=>{await save('management_coaches',crypto.randomUUID(),{...v,salary:money(v.salary)});form.reset();});}}><h2>إضافة مدرب</h2><label>اسم المدرب<input name="name" required/></label><label>الراتب المرجعي للشهور الجديدة<input name="salary" type="number" min="0" step="0.01" required/></label><BranchField/><button disabled={busy}>إضافة</button></form></>}
 {['attendance','payroll','notes'].includes(tab)&&<><section className="panel"><label>اختر المدرب<select value={coachId} onChange={e=>setCoachId(e.target.value)}><option value="">اختر…</option>{coaches.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label>{!coach&&<p className="empty">اختر مدربًا لعرض ملفه وتسجيل البيانات، أو أضف مدربًا من قسم ملفات المدربين.</p>}</section>{coach&&tab!=='notes'&&<><section className="panel"><h2>{coach.name} · {month}</h2>{!record?<><p>لا يوجد سجل لهذا الشهر. اعتماد راتب الشهر لا يؤثر على أي شهر آخر.</p>{allowed('payroll')?<form className="inline" onSubmit={e=>{const v=formData(e);act(()=>mutateMonth(latest=>{if(latest)throw Error('السجل موجود بالفعل. أعد فتحه.');return {coachId,month,branch:coach.branch,salary:money(v.salary),attendance:{},paid:0};}));}}><label>راتب هذا الشهر<input key={coachId+month} name="salary" type="number" min="0" step="0.01" required defaultValue={coach.salary}/></label><button disabled={busy}>اعتماد راتب الشهر</button></form>:<p>يجب على مسؤول الرواتب اعتماد سجل الشهر أولاً.</p>}</>:<><div className="cards">{Object.entries({days:'أيام الحضور',earned:'المستحق',paid:'المدفوع',remaining:'المتبقي'}).map(([key,label])=><div key={key}><p>{label}</p><h2>{payroll(record)[key]}</h2></div>)}</div><p>راتب الشهر: {fmt(record.salary)} د.أ · الراتب ÷ 26 × أيام الحضور، بسقف الراتب الكامل.</p>{record.closed&&<p className="notice">الشهر مقفل؛ الحضور والراتب محفوظان.</p>}{allowed('payroll')&&!record.closed&&<button className="quiet" disabled={busy} onClick={()=>{if(confirm('إقفال الشهر ومنع تغيير حضوره وراتبه؟'))act(()=>mutateMonth(r=>({...r,closed:true})));}}>إقفال الشهر</button>}</>}</section>
 {record&&tab==='attendance'&&<section className="panel"><h2>تسجيل الحضور — الإدارة فقط</h2><div className="days">{Array.from({length:new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).getDate()},(_,i)=>{const date=month+'-'+String(i+1).padStart(2,'0');return <button key={date} disabled={busy||record.closed||date>new Date().toISOString().slice(0,10)} aria-pressed={!!record.attendance?.[date]} className={record.attendance?.[date]?'present':''} onClick={()=>act(()=>mutateMonth(r=>{if(!r||r.closed)throw Error('الشهر غير متاح للتعديل.');const next={...r,attendanceDate:date,attendance:{...r.attendance,[date]:!r.attendance?.[date]}};if(payroll(next).remaining<0)throw Error('هذا التعديل يجعل المدفوع أكبر من المستحق.');return next;}))}>{i+1}<small>{record.attendance?.[date]?'حاضر':Object.hasOwn(record.attendance||{},date)?'غائب':'غير مسجل'}</small></button>;})}</div></section>}
 {record&&tab==='payroll'&&<><form className="panel inline" onSubmit={e=>{const v=formData(e),form=e.currentTarget;act(async()=>{await addPayment(v);form.reset();});}}><h2>دفعة راتب أو سلفة</h2><p>السلفة تُخصم من المتبقي وتُسجل كمصروف مرة واحدة، ضمن المستحق المتاح.</p><label>نوع الدفعة<select name="kind"><option value="salary">دفعة راتب</option><option value="advance">سلفة من الراتب</option></select></label><label>المبلغ<input name="amount" type="number" step="0.01" min="0.01" max={payroll(record).remaining} required/></label><label>تاريخ الدفع<input name="date" lang="en" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></label><button disabled={busy||payroll(record).remaining<=0}>تسجيل الدفعة والمصروف معاً</button></form><section className="panel"><Rows rows={(data.management_ledger||[]).filter(r=>r.coachId===coachId&&r.month===month)}/></section></>}
 </>}{coach&&tab==='notes'&&<><form className="panel" onSubmit={e=>{const v=formData(e),form=e.currentTarget;act(async()=>{await save('management_notes',crypto.randomUUID(),{...v,coachId,branch:coach.branch,date:new Date().toISOString().slice(0,10),createdBy:user.email});form.reset();});}}><h2>ملاحظة إدارية عن {coach.name}</h2><textarea name="text" rows="4" required/><button disabled={busy}>حفظ الملاحظة</button></form>{(data.management_notes||[]).filter(r=>r.coachId===coachId).map(n=><article className="panel" key={n.id}><small>{n.date}</small><p className="pre">{n.text}</p></article>)}</>}</>}
 {tab==='access'&&user.isSuper&&<AccessPanel users={data.management_users||[]} busy={busy} onSave={async(id,values)=>{let ok=false;await act(async()=>{await save('management_users',id,values);ok=true;});return ok;}}/>}
 </main></div>;
}
function BranchField(){return <label>الفرع<select name="branch"><option>شفا بدران</option><option>أبو نصير</option></select></label>}
function StudentRows({rows}){return <div className="table"><table><thead><tr><th>الطالب</th><th>الفرع</th><th>تاريخ الالتحاق</th><th>نهاية الاشتراك</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}><td>{r.name||r.studentName||'—'}</td><td>{r.branch||'—'}</td><td>{dayString(r.joinDate)||'—'}</td><td>{dayString(r.subEnd)||'غير محدد'}</td></tr>)}</tbody></table>{!rows.length&&<p className="empty">لا توجد سجلات مطابقة.</p>}</div>}
function Rows({rows}){const[search,setSearch]=useState(''),[type,setType]=useState('all');const list=rows.filter(r=>(type==='all'||(type==='income'?r.kind==='income':r.kind!=='income'))&&[r.name,r.title,r.studentName,r.sid,r.reason,r.branch].some(v=>String(v||'').includes(search.trim())));return <><div className="table-toolbar"><label>بحث في الكشف<input placeholder="اسم أو بيان أو فرع" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>نوع الحركة<select value={type} onChange={e=>setType(e.target.value)}><option value="all">جميع الحركات</option><option value="income">الدخل</option><option value="expense">المصروفات والدفعات</option></select></label><span>{list.length} سجل</span></div>{!list.length?<p className="empty">لا توجد سجلات مطابقة.</p>:<div className="table"><table><thead><tr><th>البيان</th><th>التاريخ</th><th>الفرع</th><th>المصدر</th><th>النوع</th><th>المبلغ (د.أ)</th></tr></thead><tbody>{list.map((r,i)=><tr key={r.id+'_'+i}><td>{r.name||r.title||r.studentName||r.sid||r.reason||'سجل'}</td><td>{dayString(r.date)||'—'}</td><td>{r.branch||'—'}</td><td>{r.source||'—'}</td><td><span className={'badge '+(r.kind==='income'?'good':'')}>{r.kind==='income'?'دخل':r.kind==='advance'?'سلفة':r.kind==='salary'?'راتب':r.kind?'مصروف':'—'}</span></td><td className="amount">{r.amount!=null?fmt(r.amount):'—'}</td></tr>)}</tbody></table></div>}</>}
