import ClubPages from './ClubPages';
import {MANAGEMENT_CLUB_PAGES,isManagementClubPage} from '../src/lib/portalPages';
import {downloadDatabaseBackup} from '../src/lib/databaseBackup';
import React,{useEffect,useState} from 'react';

import {collection,doc,onSnapshot,setDoc,runTransaction,query,where} from 'firebase/firestore';
import {db} from '../src/lib/firebase';
const path=['artifacts','brave-academy-live-data','public','data'];
import {payroll,totals,dayString,money} from './domain.mjs';

const currentMonth=`${new Date().getFullYear()}-${String(new Date().getMonth()+1).padStart(2,'0')}`;
const sections={...MANAGEMENT_CLUB_PAGES,backup:'باك اب داتابيس',overview:'نظرة عامة',finance:'الحركة المالية',coaches:'المدربون',attendance:'حضور المدربين',payroll:'الرواتب والسلف',notes:'ملاحظات المدربين',access:'صلاحيات المشرفين'};
const fmt=n=>Number(n||0).toLocaleString('ar-JO',{minimumFractionDigits:2,maximumFractionDigits:2});
const legacy=['students','payments','expenses','income_extra','debts'];
const fresh=['management_coaches','management_months','management_ledger','management_notes','management_users'];
const demo=import.meta.env.DEV && new URLSearchParams(location.search).get('demo')==='1';
const demoData={students:[{id:'s1',name:'طالب تجريبي',branch:'شفا بدران',subEnd:'2099-01-01'}],payments:[{id:'p1',studentName:'طالب تجريبي',amount:520,date:currentMonth+'-01',branch:'شفا بدران'}],expenses:[{id:'e1',title:'إيجار تجريبي',amount:150,date:currentMonth+'-01',branch:'شفا بدران'}],income_extra:[],debts:[],management_coaches:[{id:'c1',name:'مدرب تجريبي',salary:520,branch:'شفا بدران'}],management_months:[{id:'c1_'+currentMonth,coachId:'c1',month:currentMonth,salary:520,paid:0,attendance:{[currentMonth+'-01']:true,[currentMonth+'-02']:true},branch:'شفا بدران'}],management_ledger:[],management_notes:[],management_users:[]};
export default function ManagementPortal({account,onLogout}){
 const user=account;
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[data,setData]=useState(demo?demoData:{}),[loads,setLoads]=useState({}),[tab,setTab]=useState('overview'),[month,setMonth]=useState(currentMonth),[branch,setBranch]=useState('all'),[coachId,setCoachId]=useState(''),[detail,setDetail]=useState(null);
 const allowed=key=>user?.isSuper===true || (!['captains','backup','access'].includes(key)&&user?.permissions?.includes(key));
 const permissionKey=JSON.stringify(user);
 useEffect(()=>{if(!user||demo)return;const available=[...(allowed('overview')||allowed('finance')?legacy:[]),...(allowed('coaches')||allowed('attendance')||allowed('payroll')||allowed('notes')?['management_coaches']:[]),...(allowed('attendance')||allowed('payroll')||allowed('overview')?['management_months']:[]),...(allowed('finance')||allowed('payroll')||allowed('overview')?['management_ledger']:[]),...(allowed('notes')?['management_notes']:[]),...(user.isSuper?['management_users']:[])];setLoads(Object.fromEntries(available.map(n=>[n,'loading'])));return (()=>{const stops=available.map(name=>onSnapshot(name==='management_ledger'&&!allowed('finance')&&!allowed('overview')?query(collection(db,...path,name),where('kind','in',['salary','advance'])):collection(db,...path,name),snapshot=>{setData(old=>({...old,[name]:snapshot.docs.map(d=>({...d.data(),id:d.id}))}));setLoads(old=>({...old,[name]:'ready'}));},()=>setLoads(old=>({...old,[name]:'error'}))));return ()=>stops.forEach(stop=>stop());})();},[permissionKey]);
 useEffect(()=>{if(user&&!allowed(tab)){setTab(Object.keys(sections).find(key=>key!=='access'&&allowed(key))||'none');}},[permissionKey,tab]);
 const act=async fn=>{if(busy)return;setBusy(true);setError('');try{await fn();}catch(e){setError(e.message||'تعذر الحفظ. حاول مرة أخرى.');}finally{setBusy(false);}};
 const save=async(name,id,record)=>{if(!fresh.includes(name))throw Error('الكتابة على بيانات النظام الحالي غير مسموحة.');if(demo){setData(old=>({...old,[name]:[...(old[name]||[]).filter(r=>r.id!==id),{...record,id}]}));return;}await setDoc(doc(db,...path,name,id),record);};
 const coaches=(data.management_coaches||[]).filter(c=>branch==='all'||c.branch===branch),coach=coaches.find(c=>c.id===coachId),record=(data.management_months||[]).find(r=>r.coachId===coachId&&r.month===month),summary=totals(data,month,branch);
 const mutateMonth=async change=>{const id=coachId+'_'+month;if(demo){const latest=(data.management_months||[]).find(r=>r.id===id);await save('management_months',id,change(latest));return;}await runTransaction(db,async tx=>{const ref=doc(db,...path,'management_months',id),snapshot=await tx.get(ref);tx.set(ref,change(snapshot.exists()?snapshot.data():null));});};
 const formData=e=>{e.preventDefault();return Object.fromEntries(new FormData(e.currentTarget));};
 const addPayment=async values=>{const id=crypto.randomUUID();const amount=money(values.amount);if(amount<=0)throw Error('أدخل مبلغاً موجباً.');const entry={kind:values.kind==='advance'?'advance':'salary',coachId,month,amount,date:values.date,branch:coach.branch,title:`${values.kind==='advance'?'سلفة':'راتب'} ${coach.name} — ${month}`,createdBy:user.email};if(demo){if(!record||amount>payroll(record).remaining)throw Error('المبلغ يتجاوز المتبقي المستحق.');await save('management_months',record.id,{...record,paid:money(Number(record.paid||0)+amount)});await save('management_ledger',id,entry);return;}await runTransaction(db,async tx=>{const ref=doc(db,...path,'management_months',record.id),snap=await tx.get(ref);if(!snap.exists()||amount>payroll(snap.data()).remaining)throw Error('المبلغ يتجاوز المتبقي المستحق.');tx.update(ref,{paid:money(Number(snap.data().paid||0)+amount),lastPayment:id});tx.set(doc(db,...path,'management_ledger',id),entry);});};
 const pending=Object.values(loads).some(v=>v==='loading'),failed=Object.entries(loads).filter(([,v])=>v==='error');
 return <div className="layout"><aside><div className="eyebrow">Brave Taekwondo</div><h2>الإدارة</h2><p>{user.isSuper?'المدير':'المشرف'}</p><nav>{Object.entries(sections).filter(([key])=>key==='access'?user.isSuper:allowed(key)).map(([key,label])=><button className={tab===key?'selected':''} key={key} onClick={()=>{setTab(key);setDetail(null);setError('');}}>{label}</button>)}</nav><a href="/">تطبيق النادي ↗</a><button className="quiet" onClick={()=>onLogout()}>تسجيل الخروج</button></aside><main><header><div><div className="eyebrow">مركز إدارة النادي</div><h1>{sections[tab]||'لا توجد صلاحيات مفعلة'}</h1></div><div className="filters"><label>الشهر<input type="month" value={month} onChange={e=>{setMonth(e.target.value);setDetail(null);}} required/></label><label>الفرع<select value={branch} onChange={e=>{setBranch(e.target.value);setCoachId('');}}><option value="all">جميع الفروع</option><option>شفا بدران</option><option>أبو نصير</option></select></label></div></header>{demo&&<p className="notice">معاينة ببيانات تجريبية — لا تقرأ أو تعدّل بيانات النادي</p>}{error&&<p role="alert" className="error">{error}</p>}{pending&&<p className="notice">جارٍ تحميل السجلات…</p>}{failed.length>0&&<p role="alert" className="error">تعذر تحميل: {failed.map(([n])=>n).join('، ')}. الملخصات غير مكتملة؛ لا تعتمد أرقامها حتى يتصل المصدر.</p>}
 {tab==='overview'&&!pending&&!failed.length&&<><section className="cards">{[['الطلاب المسجلون',summary.students.length,summary.students],['الطلاب النشطون',summary.students.filter(s=>dayString(s.subEnd)>=dayString(new Date().toISOString())).length,summary.students.filter(s=>dayString(s.subEnd)>=dayString(new Date().toISOString()))],['اشتراكات منتهية',summary.students.filter(s=>!s.subEnd||dayString(s.subEnd)<new Date().toISOString().slice(0,10)).length,summary.students.filter(s=>!s.subEnd||dayString(s.subEnd)<new Date().toISOString().slice(0,10))],['طلاب التحقوا هذا الشهر',summary.students.filter(s=>dayString(s.joinDate).startsWith(month)).length,summary.students.filter(s=>dayString(s.joinDate).startsWith(month))],['ذمم الطلاب الحالية',fmt((data.debts||[]).filter(r=>branch==='all'||r.branch===branch).reduce((n,r)=>n+Math.max(0,Number(r.totalAmount||0)-Number(r.paidAmount||0)),0)),(data.debts||[]).filter(r=>(branch==='all'||r.branch===branch)&&Number(r.totalAmount||0)>Number(r.paidAmount||0)).map(r=>({...r,amount:money(Number(r.totalAmount||0)-Number(r.paidAmount||0))}))],['وصولات الطلاب',fmt(summary.receipts.reduce((n,r)=>n+Number(r.amount||0),0)),summary.receipts],['إجمالي الدخل',fmt(summary.income),[...summary.receipts,...summary.extra,...summary.ledger.filter(r=>r.kind==='income')]],['المصروفات والرواتب المدفوعة',fmt(summary.outgoing),[...summary.expenses,...summary.ledger.filter(r=>r.kind!=='income')]],['صافي الحركة المالية',fmt(summary.net),null]].map(([label,value,rows])=><button className="metric" key={label} onClick={()=>rows&&setDetail({label,rows})}><span>{label}</span><strong>{value}</strong><small>{rows?'عرض التفاصيل ←':'الدخل ناقص المصروفات · د.أ'}</small></button>)}</section><section className="panel"><h2>رواتب {month}</h2><div className="cards">{['earned','paid','remaining'].map((key,i)=><div key={key}><p>{['المستحق','المدفوع','المتبقي'][i]}</p><h2>{fmt((data.management_months||[]).filter(r=>r.month===month&&(branch==='all'||r.branch===branch)).reduce((n,r)=>n+payroll(r)[key],0))} د.أ</h2></div>)}</div><p>أعداد الطلاب وحالة الاشتراك حسب الوضع الحالي؛ الحركة المالية حسب الشهر المختار.</p></section></>}
 {isManagementClubPage(tab)&&allowed(tab)&&<ClubPages key={tab+branch} page={tab} branch={branch} user={user}/>}
 {tab==='backup'&&user.isSuper&&<section className="panel"><h2>نسخة بيانات جميع الفروع</h2><p>تُقرأ السجلات مباشرة من قاعدة البيانات، وتشمل الطلاب والمالية والمخزون وحضور المدربين ورواتبهم والسلف والصلاحيات. يتوقف التنزيل إذا تعذر تحميل أي مجموعة.</p><p>هذا الملف لا يشمل ملفات الصور والمرفقات ولا حسابات Firebase Authentication؛ تحتاج نسخة خادم منفصلة للاستعادة الكاملة.</p><button disabled={busy} onClick={()=>act(async()=>{if(demo)throw Error('النسخ الاحتياطي غير متاح في العرض التجريبي.');await downloadDatabaseBackup();})}>{busy?'جارٍ إعداد النسخة…':'تحميل النسخة الاحتياطية'}</button></section>}
 {detail&&<section className="panel"><button className="quiet" onClick={()=>setDetail(null)}>إغلاق التفاصيل ×</button><h2>{detail.label}</h2><Rows rows={detail.rows}/></section>}
 {tab==='finance'&&<><section className="panel"><h2>سجل الداخل والخارج</h2><p>الوصولات والمصروفات القديمة للعرض. الحركات الجديدة محفوظة في بوابة الإدارة.</p><Rows rows={[...summary.receipts.map(r=>({...r,title:r.studentName||r.sid||'وصل طالب',kind:'income'})),...summary.extra.map(r=>({...r,kind:'income'})),...summary.expenses.map(r=>({...r,kind:'expense'})),...summary.ledger].sort((a,b)=>dayString(b.date).localeCompare(dayString(a.date)))}/></section><form className="panel inline" onSubmit={e=>{const v=formData(e),form=e.currentTarget;act(async()=>{await save('management_ledger',crypto.randomUUID(),{...v,amount:money(v.amount),createdBy:user.email});form.reset();});}}><h2>حركة مالية جديدة</h2><label>النوع<select name="kind"><option value="income">دخل إضافي</option><option value="expense">مصروف</option></select></label><label>البيان<input name="title" required/></label><label>المبلغ<input name="amount" type="number" min="0.01" step="0.01" required/></label><label>التاريخ<input name="date" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></label><BranchField/><button disabled={busy}>حفظ الحركة</button></form></>}
 {tab==='coaches'&&<><section className="panel"><h2>المدربون في البوابة الجديدة</h2><Rows rows={coaches.map(c=>({...c,title:c.name,amount:c.salary}))}/></section><form className="panel inline" onSubmit={e=>{const v=formData(e),form=e.currentTarget;act(async()=>{await save('management_coaches',crypto.randomUUID(),{...v,salary:money(v.salary)});form.reset();});}}><h2>إضافة مدرب</h2><label>اسم المدرب<input name="name" required/></label><label>الراتب المرجعي للشهور الجديدة<input name="salary" type="number" min="0" step="0.01" required/></label><BranchField/><button disabled={busy}>إضافة</button></form></>}
 {['attendance','payroll','notes'].includes(tab)&&<><section className="panel"><label>اختر المدرب<select value={coachId} onChange={e=>setCoachId(e.target.value)}><option value="">اختر…</option>{coaches.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label></section>{coach&&tab!=='notes'&&<><section className="panel"><h2>{coach.name} · {month}</h2>{!record?<><p>لا يوجد سجل لهذا الشهر. اعتماد راتب الشهر لا يؤثر على أي شهر آخر.</p>{allowed('payroll')?<form className="inline" onSubmit={e=>{const v=formData(e);act(()=>mutateMonth(latest=>{if(latest)throw Error('السجل موجود بالفعل. أعد فتحه.');return {coachId,month,branch:coach.branch,salary:money(v.salary),attendance:{},paid:0};}));}}><label>راتب هذا الشهر<input key={coachId+month} name="salary" type="number" min="0" step="0.01" required defaultValue={coach.salary}/></label><button disabled={busy}>اعتماد راتب الشهر</button></form>:<p>يجب على مسؤول الرواتب اعتماد سجل الشهر أولاً.</p>}</>:<><div className="cards">{Object.entries({days:'أيام الحضور',earned:'المستحق',paid:'المدفوع',remaining:'المتبقي'}).map(([key,label])=><div key={key}><p>{label}</p><h2>{payroll(record)[key]}</h2></div>)}</div><p>راتب الشهر: {fmt(record.salary)} د.أ · الراتب ÷ 26 × أيام الحضور، بسقف الراتب الكامل.</p>{record.closed&&<p className="notice">الشهر مقفل؛ الحضور والراتب محفوظان.</p>}{allowed('payroll')&&!record.closed&&<button className="quiet" disabled={busy} onClick={()=>{if(confirm('إقفال الشهر ومنع تغيير حضوره وراتبه؟'))act(()=>mutateMonth(r=>({...r,closed:true})));}}>إقفال الشهر</button>}</>}</section>
 {record&&tab==='attendance'&&<section className="panel"><h2>تسجيل الحضور — الإدارة فقط</h2><div className="days">{Array.from({length:new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).getDate()},(_,i)=>{const date=month+'-'+String(i+1).padStart(2,'0');return <button key={date} disabled={busy||record.closed||date>new Date().toISOString().slice(0,10)} aria-pressed={!!record.attendance?.[date]} className={record.attendance?.[date]?'present':''} onClick={()=>act(()=>mutateMonth(r=>{if(!r||r.closed)throw Error('الشهر غير متاح للتعديل.');const next={...r,attendance:{...r.attendance,[date]:!r.attendance?.[date]}};if(payroll(next).remaining<0)throw Error('هذا التعديل يجعل المدفوع أكبر من المستحق.');return next;}))}>{i+1}<small>{record.attendance?.[date]?'حاضر':Object.hasOwn(record.attendance||{},date)?'غائب':'غير مسجل'}</small></button>;})}</div></section>}
 {record&&tab==='payroll'&&<><form className="panel inline" onSubmit={e=>{const v=formData(e),form=e.currentTarget;act(async()=>{await addPayment(v);form.reset();});}}><h2>دفعة راتب أو سلفة</h2><p>السلفة تُخصم من المتبقي وتُسجل كمصروف مرة واحدة، ضمن المستحق المتاح.</p><label>نوع الدفعة<select name="kind"><option value="salary">دفعة راتب</option><option value="advance">سلفة من الراتب</option></select></label><label>المبلغ<input name="amount" type="number" step="0.01" min="0.01" max={payroll(record).remaining} required/></label><label>تاريخ الدفع<input name="date" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></label><button disabled={busy||payroll(record).remaining<=0}>تسجيل الدفعة والمصروف معاً</button></form><section className="panel"><Rows rows={(data.management_ledger||[]).filter(r=>r.coachId===coachId&&r.month===month)}/></section></>}
 </>}{coach&&tab==='notes'&&<><form className="panel" onSubmit={e=>{const v=formData(e),form=e.currentTarget;act(async()=>{await save('management_notes',crypto.randomUUID(),{...v,coachId,branch:coach.branch,date:new Date().toISOString().slice(0,10),createdBy:user.email});form.reset();});}}><h2>ملاحظة إدارية عن {coach.name}</h2><textarea name="text" rows="4" required/><button disabled={busy}>حفظ الملاحظة</button></form>{(data.management_notes||[]).filter(r=>r.coachId===coachId).map(n=><article className="panel" key={n.id}><small>{n.date}</small><p className="pre">{n.text}</p></article>)}</>}</>}
 {tab==='access'&&user.isSuper&&<><form className="panel" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);act(()=>save('management_users',String(f.get('email')).trim().toLowerCase(),{active:true,permissions:f.getAll('permissions')}));}}><h2>منح صلاحيات لمشرف</h2><p>أدخل بريد حساب مسجل مسبقاً. هذه الصلاحيات تخص البوابة الجديدة فقط.</p><label>البريد الإلكتروني<input name="email" type="email" required/></label><div className="checks">{Object.entries(sections).filter(([key])=>!['access','captains','backup'].includes(key)).map(([key,label])=><label key={key}><input type="checkbox" name="permissions" value={key}/>{label}</label>)}</div><button disabled={busy}>حفظ الصلاحيات المختارة</button></form><section className="panel">{(data.management_users||[]).map(u=><div className="user" key={u.id}><b>{u.id}</b><span>{u.permissions?.map(p=>sections[p]).join('، ')}</span><button disabled={busy} className="quiet" onClick={()=>act(()=>save('management_users',u.id,{active:!u.active,permissions:u.permissions||[]}))}>{u.active?'إيقاف الوصول':'تفعيل الوصول'}</button></div>)}</section></>}
 </main></div>;
}
function BranchField(){return <label>الفرع<select name="branch"><option>شفا بدران</option><option>أبو نصير</option></select></label>}
function Rows({rows}){return !rows.length?<p className="empty">لا توجد سجلات مطابقة.</p>:<div className="table"><table><thead><tr><th>الاسم / البيان</th><th>التاريخ</th><th>الفرع</th><th>المبلغ / النوع</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id+'_'+i}><td>{r.name||r.title||r.studentName||r.sid||r.reason||'سجل'}</td><td>{dayString(r.date)||'—'}</td><td>{r.branch||'—'}</td><td>{r.amount!=null?fmt(r.amount)+' د.أ':'—'} {r.kind==='income'?'· دخل':r.kind==='advance'?'· سلفة':r.kind?'· مصروف':''}</td></tr>)}</tbody></table></div>}

