import React,{useState} from 'react';
import {LayoutDashboard,Wallet,Users,CalendarDays,Package,Newspaper,BarChart3,Shield,Database,Menu,X,LogOut,ChevronLeft} from 'lucide-react';
export const ADMIN_AREAS=[
 {title:'لوحة الإدارة',items:[['overview','ملخص النادي',LayoutDashboard]]},
 {title:'الشؤون المالية',items:[['finance','الحسابات والحركة المالية',Wallet],['reports','التقارير والكشوف',BarChart3]]},
 {title:'فريق التدريب',items:[['coaches','ملفات المدربين',Users],['attendance','الحضور والغياب',CalendarDays],['payroll','الرواتب والسلف',Wallet],['notes','الملاحظات الإدارية',Newspaper]]},
 {title:'تشغيل النادي',items:[['schedule','جدول الحصص',CalendarDays],['inventory','المخزون والتجهيزات',Package],['news','الأخبار والعروض',Newspaper]]},
 {title:'الإعدادات والصلاحيات',items:[['captains','حسابات تطبيق النادي',Shield],['access','صلاحيات الإدارة',Shield],['backup','النسخ الاحتياطي',Database]]},
];
export const PAGE_HELP={overview:'مؤشرات النادي المالية والتشغيلية في مكان واحد.',finance:'وصولات الطلاب والدخل والمصروفات ودفعات المدربين، بسجل موحّد.',reports:'كشوف تفصيلية للمراجعة والطباعة حسب الفرع والشهر.',coaches:'ملف لكل مدرب وراتبه المرجعي للشهور القادمة.',attendance:'تسجيل ومراجعة أيام حضور المدربين للشهر المحدد.',payroll:'اعتماد راتب كل شهر ومتابعة المستحق والدفعات والسلف.',notes:'ملاحظات داخلية مرتبطة بكل مدرب.',schedule:'تنظيم مواعيد الحصص والمستويات والفروع.',inventory:'الأصناف والمقاسات وكميات المخزون وحركة التوريد والصرف.',news:'إدارة المحتوى المنشور للطلاب وأولياء الأمور.',captains:'إدارة حسابات وصلاحيات العاملين في تطبيق النادي.',access:'تحديد وصول المشرفين إلى أقسام الإدارة.',backup:'تصدير نسخة من بيانات النادي وحفظها لديك.'};
export function Sidebar({tab,allowed,onNavigate,user,onLogout}){
 const[open,setOpen]=useState(false),[search,setSearch]=useState('');
 return <><button className="mobile-menu quiet" onClick={()=>setOpen(!open)} aria-expanded={open} aria-label="قائمة الإدارة">{open?<X size={20}/>:<Menu size={20}/>} الأقسام</button>{open&&<button className="nav-overlay" onClick={()=>setOpen(false)} aria-label="إغلاق القائمة"/>}<aside className={'admin-sidebar '+(open?'is-open':'')}><div className="brand-lockup"><div className="brand-mark">B</div><div><strong>اكاديمية الشجاع</strong><small>Brave Taekwondo</small></div></div><div className="workspace-label">الإدارة العامة <span>مساحة الإدارة</span></div><input className="nav-search" placeholder="ابحث عن قسم…" aria-label="البحث في أقسام الإدارة" value={search} onChange={e=>setSearch(e.target.value)}/><nav aria-label="أقسام الإدارة">{ADMIN_AREAS.map(area=>{const items=area.items.filter(([key,label])=>allowed(key)&&label.includes(search.trim()));return items.length>0&&<section className="nav-group" key={area.title}><h3>{area.title}</h3>{items.map(([key,label,Icon])=><button key={key} aria-current={tab===key?'page':undefined} className={tab===key?'selected':''} onClick={()=>{onNavigate(key);setOpen(false);}}><Icon size={18}/><span>{label}</span>{tab===key&&<ChevronLeft size={14}/>}</button>)}</section>;})}</nav><div className="sidebar-footer"><small>{user.isSuper?'المدير العام':'حساب مشرف'}</small><span>{user.name||user.email}</span><a href="/">الانتقال لتطبيق النادي ↗</a><button onClick={onLogout}><LogOut size={16}/> تسجيل الخروج</button></div></aside></>;
}
export function SectionTabs({tab,allowed,onNavigate}){const area=ADMIN_AREAS.find(a=>a.items.some(([key])=>key===tab));return area&&area.items.filter(([key])=>allowed(key)).length>1?<nav className="section-tabs" aria-label={area.title}>{area.items.filter(([key])=>allowed(key)).map(([key,label])=><button key={key} className={tab===key?'selected':''} aria-current={tab===key?'page':undefined} onClick={()=>onNavigate(key)}>{label}</button>)}</nav>:null;}
