import {catalogUpdate} from './catalog.mjs';
import React,{useState,useRef} from 'react';
import {doc,collection,runTransaction} from 'firebase/firestore';
import {ref,uploadBytes,getDownloadURL} from 'firebase/storage';
import {db,appId,storage} from '../src/lib/firebase';
import {useCollection} from '../src/hooks/useCollection';
const base=['artifacts',appId,'public','data'];
const seeds={schedule:[{id:'s',level:'المجموعة الأساسية',days:'السبت، الاثنين، الأربعاء',time:'17:00',branch:'شفا بدران'}],news:[{id:'n',title:'مواعيد التدريب',desc:'مثال توضيحي لبطاقة خبر.',branch:'شفا بدران'}],products:[{id:'p',name:'بدلة تدريب',price:25,categoryId:'c',lowStockAlert:3,variants:[{size:'140',stock:8},{size:'150',stock:2}],branch:'شفا بدران'}],product_categories:[{id:'c',name:'ملابس التدريب'}],inventory_log:[]};
function useRecords(name,enabled,demo){const live=useCollection(name,{enabled:enabled&&!demo});const[data,set]=useState(seeds[name]||[]);return demo?{data,loading:false,error:null,add:async r=>{const id=crypto.randomUUID();set(v=>[...v,{...r,id}]);return{id};},update:async(id,r)=>{set(v=>v.map(x=>x.id===id?{...x,...r}:x));return true;},remove:async id=>{set(v=>v.filter(x=>x.id!==id));return true;}}:live;}
export default function Operations({page,branch,demo}){
 const schedule=useRecords('schedule',page==='schedule',demo),news=useRecords('news',page==='news',demo),products=useRecords('products',page==='inventory',demo),categories=useRecords('product_categories',page==='inventory',demo),logs=useRecords('inventory_log',page==='inventory',demo);
 const[search,setSearch]=useState(''),[editor,setEditor]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[category,setCategory]=useState('all');const guard=useRef(false);
 const cols=page==='schedule'?[schedule]:page==='news'?[news]:[products,categories,logs];
 const act=async fn=>{if(guard.current)return;guard.current=true;setBusy(true);setError('');setNotice('');try{await fn();setNotice('تم حفظ التغيير بنجاح.');}catch(e){setError(e.message||'تعذر الحفظ. حاول مرة أخرى.');}finally{guard.current=false;setBusy(false);}};
 const checked=async p=>{if(!await p)throw Error('تعذر حفظ التغيير. البيانات المدخلة ما زالت متاحة.');};
 const updateProduct=async(product,values)=>{if(demo)return products.update(product.id,catalogUpdate(products.data.find(p=>p.id===product.id),values));await runTransaction(db,async tx=>{const target=doc(db,...base,'products',product._docId||product.id),snapshot=await tx.get(target);if(!snapshot.exists())throw Error('الصنف غير متاح.');tx.update(target,catalogUpdate(snapshot.data(),values));});return true;};
 const store=page==='schedule'?schedule:page==='news'?news:products;
 const rows=store.data.filter(r=>(branch==='all'||r.branch===branch||r.branch==='الكل')&&String(r.name||r.title||r.level||'').includes(search.trim())&&(page!=='inventory'||category==='all'||r.categoryId===category));
 if(cols.some(c=>c.loading))return <div className="panel empty">جارٍ تحميل سجلات القسم…</div>;
 if(cols.some(c=>c.error))return <p className="error" role="alert">تعذر تحميل سجلات القسم. تحقق من الاتصال والصلاحيات.</p>;
 const saveSimple=async e=>{e.preventDefault();const form=e.currentTarget,values=Object.fromEntries(new FormData(form));await act(async()=>{const payload=page==='schedule'?{level:values.level.trim(),days:values.days.trim(),time:values.time,branch:editor.id?editor.branch:values.branch}:{title:values.title.trim(),desc:values.desc.trim(),branch:editor.id?editor.branch:values.branch,image:editor.image||''};if(page==='news'){const file=form.elements.imageFile.files[0];if(file){if(file.size>5*1024*1024)throw Error('اختر صورة أصغر من 5 ميغابايت.');if(demo)payload.image=URL.createObjectURL(file);else{const uploaded=await uploadBytes(ref(storage,'news/'+crypto.randomUUID()),file);payload.image=await getDownloadURL(uploaded.ref);}}}await checked(editor.id?store.update(editor._docId||editor.id,payload):store.add({...payload,createdAt:new Date().toISOString()}));setEditor(null);});};
 return <><div className="section-toolbar"><label>البحث<input aria-label="البحث في القسم" placeholder={page==='inventory'?'اسم الصنف':'عنوان أو مستوى'} value={search} onChange={e=>setSearch(e.target.value)}/></label>{page==='inventory'&&<label>تصنيف المخزون<select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">جميع الأصناف</option>{categories.data.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}<button onClick={()=>setEditor({branch:branch==='all'?'شفا بدران':branch})} disabled={busy}>＋ {page==='schedule'?'إضافة حصة':page==='news'?'خبر أو عرض جديد':'إضافة صنف'}</button><span className="badge">{rows.length} سجل</span></div>{error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="success" role="status">{notice}</p>}
 {editor&&page!=='inventory'&&<section className="panel editor-panel"><div className="panel-heading"><h2>{editor.id?'تعديل السجل':page==='schedule'?'حصة جديدة':'إعداد خبر أو عرض'}</h2><button className="quiet" disabled={busy} onClick={()=>setEditor(null)}>إلغاء ×</button></div><form key={editor.id||'new'} onSubmit={saveSimple}><div className="form-grid">{page==='schedule'?<><label>المستوى / المجموعة<input name="level" required defaultValue={editor.level} maxLength={150}/></label><label>أيام التدريب<input name="days" required defaultValue={editor.days} placeholder="السبت، الاثنين، الأربعاء"/></label><label>وقت الحصة<input name="time" required defaultValue={editor.time} placeholder="17:00 – 18:00"/></label></>:<><label>عنوان الخبر<input name="title" required maxLength={200} defaultValue={editor.title}/></label><label>الصورة (اختياري)<input name="imageFile" type="file" accept="image/*"/></label></>}<label>الفرع<select name="branch" defaultValue={editor.branch} disabled={Boolean(editor.id)}><option>شفا بدران</option><option>أبو نصير</option><option>الكل</option></select></label></div>{page==='news'&&<label>المحتوى<textarea name="desc" rows="5" required defaultValue={editor.desc}/></label>}<button disabled={busy}>{busy?'جارٍ الحفظ…':page==='news'?'حفظ ونشر المحتوى':'حفظ الحصة'}</button></form></section>}
 {page==='schedule'&&<section className="panel"><h2>برنامج الحصص</h2><div className="table"><table><thead><tr><th>المستوى / المجموعة</th><th>الأيام</th><th>الوقت</th><th>الفرع</th><th>إجراءات</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.level}</strong></td><td>{r.days}</td><td>{r.time}</td><td><span className="badge">{r.branch}</span></td><td><Actions row={r}/></td></tr>)}</tbody></table></div>{!rows.length&&<p className="empty">لا توجد حصص مطابقة. أضف حصة لتظهر في جدول النادي.</p>}</section>}
 {page==='news'&&<div className="news-grid">{rows.map(r=><article className="panel news-card" key={r.id}>{r.image&&<img src={r.image} alt=""/>}<span className="badge">{r.branch}</span><h2>{r.title}</h2><p className="pre">{r.desc}</p><Actions row={r}/></article>)}{!rows.length&&<div className="panel empty">لا توجد أخبار أو عروض مطابقة.</div>}</div>}
 {page==='inventory'&&<><section className="cards"><div className="metric"><span>الأصناف المعروضة</span><strong>{rows.length}</strong></div><div className="metric"><span>القطع المتاحة</span><strong>{rows.reduce((n,p)=>n+(p.variants||[]).reduce((a,v)=>a+Number(v.stock||0),0),0)}</strong></div><div className="metric"><span>أصناف تحتاج تزويد</span><strong>{rows.filter(p=>(p.variants||[]).some(v=>Number(v.stock)<=Number(p.lowStockAlert??3))).length}</strong></div></section>
 {editor&&<ProductEditor key={editor.id||'new'} product={editor} categories={categories.data} busy={busy} onCancel={()=>setEditor(null)} onSave={values=>act(async()=>{await checked(editor.id?updateProduct(editor,values):products.add({...values,createdAt:new Date().toISOString()}));setEditor(null);})}/>}
 <details className="panel"><summary>إدارة تصنيفات المخزون</summary><form className="inline" onSubmit={e=>{e.preventDefault();const f=e.currentTarget,name=new FormData(f).get('name').trim();act(async()=>{await checked(categories.add({name,icon:'📦'}));f.reset();});}}><label>اسم التصنيف<input name="name" required maxLength={100}/></label><button disabled={busy}>إضافة تصنيف</button></form><p>{categories.data.map(c=>c.name).join(' · ')}</p></details>
 <section className="panel"><h2>الأصناف والمقاسات</h2><div className="table"><table><thead><tr><th>الصنف</th><th>التصنيف</th><th>الفرع</th><th>سعر الوحدة</th><th>إجراءات</th></tr></thead><tbody>{rows.map(p=><React.Fragment key={p.id}><tr><td><strong>{p.name}</strong></td><td>{categories.data.find(c=>c.id===p.categoryId)?.name||'بدون تصنيف'}</td><td>{p.branch}</td><td>{Number(p.price||0).toFixed(2)} د.أ</td><td><Actions row={p}/></td></tr><tr><td colSpan="5"><div className="variant-grid">{(p.variants||[]).map((v,i)=><StockControl key={i} variant={v} busy={busy} low={Number(v.stock)<=Number(p.lowStockAlert??3)} onAdjust={(delta,reason)=>act(async()=>{if(demo){const variants=p.variants.map((x,j)=>j===i?{...x,stock:Number(x.stock)+delta}:x);if(variants[i].stock<0)throw Error('الكمية أكبر من المتاح.');await checked(products.update(p.id,{variants}));await checked(logs.add({productName:p.name,variantSize:v.size,type:delta>0?'in':'out',quantity:Math.abs(delta),reason,branch:p.branch,createdAt:new Date().toISOString()}));return;}await runTransaction(db,async tx=>{const target=doc(db,...base,'products',p._docId||p.id),snapshot=await tx.get(target);if(!snapshot.exists())throw Error('الصنف غير متاح.');const latest=snapshot.data();if(latest.variants?.[i]?.size!==v.size)throw Error('تغيرت المقاسات. أعد فتح الصنف.');const stock=Number(latest.variants[i].stock)+delta;if(stock<0)throw Error('الكمية المطلوبة أكبر من المخزون المتاح.');tx.update(target,{variants:latest.variants.map((x,j)=>j===i?{...x,stock}:x)});tx.set(doc(collection(db,...base,'inventory_log')),{productId:p.id,productName:p.name,variantSize:v.size,type:delta>0?'in':'out',quantity:Math.abs(delta),reason,branch:p.branch,createdAt:new Date().toISOString()});});})}/>)}</div></td></tr></React.Fragment>)}</tbody></table></div>{!rows.length&&<p className="empty">لا توجد أصناف مطابقة.</p>}</section>
 <details className="panel"><summary>سجل حركة المخزون</summary><div className="table"><table><thead><tr><th>الصنف</th><th>المقاس</th><th>الحركة</th><th>الكمية</th><th>السبب</th><th>التاريخ</th></tr></thead><tbody>{logs.data.filter(r=>branch==='all'||r.branch===branch).sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||''))).map(r=><tr key={r.id}><td>{r.productName}</td><td>{r.variantSize}</td><td>{r.type==='in'?'توريد':'صرف'}</td><td>{r.quantity}</td><td>{r.reason}</td><td>{String(r.createdAt||'').slice(0,10)}</td></tr>)}</tbody></table></div></details></>}
 </>;
 function Actions({row}){return <div className="row-actions"><button className="quiet" disabled={busy} onClick={()=>{setError('');setEditor(row);}}>تعديل</button><button className="danger-quiet" disabled={busy} onClick={()=>{if(confirm('حذف هذا السجل؟'))act(()=>checked(store.remove(row._docId||row.id)));}}>حذف</button></div>;}
}
function ProductEditor({product,categories,busy,onCancel,onSave}){const[variants,setVariants]=useState(product.variants||[{size:'موحد',stock:0}]);return <form className="panel editor-panel" onSubmit={e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));if(new Set(variants.map(x=>x.size.trim())).size!==variants.length)return;onSave({name:v.name.trim(),price:Number(v.price),categoryId:v.categoryId,lowStockAlert:Number(v.lowStockAlert),branch:product.id?product.branch:v.branch,variants:variants.map(x=>({...x,size:x.size.trim(),stock:Number(x.stock)}))});}}><div className="panel-heading"><h2>{product.id?'تعديل الصنف':'صنف جديد'}</h2><button type="button" className="quiet" disabled={busy} onClick={onCancel}>إلغاء</button></div><div className="form-grid"><label>اسم الصنف<input name="name" required defaultValue={product.name}/></label><label>التصنيف<select name="categoryId" defaultValue={product.categoryId||''}><option value="">بدون تصنيف</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>سعر الوحدة<input name="price" type="number" min="0" step="0.01" required defaultValue={product.price??0}/></label><label>تنبيه نقص المخزون<input name="lowStockAlert" type="number" min="0" required defaultValue={product.lowStockAlert??3}/></label><label>الفرع<select name="branch" defaultValue={product.branch} disabled={Boolean(product.id)}><option>شفا بدران</option><option>أبو نصير</option></select></label></div><p>المقاسات والكميات. استخدم التوريد والصرف لتغيير مخزون صنف موجود.</p>{variants.map((v,i)=><div className="variant-row" key={i}><label>المقاس<input required value={v.size} disabled={Boolean(product.id)&&i<(product.variants||[]).length} onChange={e=>setVariants(a=>a.map((x,j)=>i===j?{...x,size:e.target.value}:x))}/></label><label>الكمية<input type="number" min="0" required value={v.stock} disabled={Boolean(product.id)&&i<(product.variants||[]).length} onChange={e=>setVariants(a=>a.map((x,j)=>i===j?{...x,stock:e.target.value}:x))}/></label></div>)}{<button type="button" className="quiet" onClick={()=>setVariants(v=>[...v,{size:'',stock:0}])}>＋ مقاس</button>}<button disabled={busy||new Set(variants.map(v=>v.size.trim())).size!==variants.length}>حفظ الصنف</button></form>;}
function StockControl({variant,low,busy,onAdjust}){return <details className={'stock-variant '+(low?'stock-low':'')}><summary>المقاس {variant.size} <b>{variant.stock} قطعة</b>{low&&<small>يحتاج تزويد</small>}</summary><form onSubmit={e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));onAdjust(Number(v.quantity)*(v.type==='in'?1:-1),v.reason.trim());}}><label>الحركة<select name="type"><option value="in">توريد</option><option value="out">صرف</option></select></label><label>الكمية<input type="number" name="quantity" min="1" required/></label><label>السبب<input name="reason" required/></label><button disabled={busy}>تسجيل الحركة</button></form></details>;}
