import React from 'react';
import {Wallet,Users,ArrowDownLeft,ArrowUpLeft,ChevronLeft} from 'lucide-react';
import {payroll,dayString} from './domain.mjs';
const num=n=>Number(n||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
export default function Overview({summary,data,month,branch,ledger,onDetails,onNavigate,allowed}){
 const today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Amman'}),active=summary.students.filter(s=>dayString(s.subEnd)>=today),expired=summary.students.filter(s=>!s.subEnd||dayString(s.subEnd)<today),joined=summary.students.filter(s=>dayString(s.joinDate).startsWith(month));
 const months=(data.management_months||[]).filter(r=>r.month===month&&(branch==='all'||r.branch===branch));
 const debts=(data.debts||[]).filter(r=>(branch==='all'||r.branch===branch)&&Number(r.totalAmount)>Number(r.paidAmount||0)).map(r=>({...r,amount:Number(r.totalAmount)-Number(r.paidAmount||0)}));
 const incomeRows=ledger.filter(r=>r.kind==='income'),outRows=ledger.filter(r=>r.kind!=='income');
 return <><section className="executive-grid"><article className="balance-card"><div className="balance-top"><span>صافي الحركة المالية</span><Wallet size={22}/></div><strong dir="ltr">{num(summary.net)} <small>JOD</small></strong><p>المقبوضات ناقص المصروفات المدفوعة</p><div className="balance-bottom"><span>{month}</span><span>{branch==='all'?'جميع الفروع':branch}</span></div></article><button className="flow-card" onClick={()=>onDetails({label:'تفاصيل الدخل',rows:incomeRows})}><span className="flow-icon income"><ArrowDownLeft size={22}/></span><span>إجمالي الدخل</span><strong dir="ltr">{num(summary.income)} <small>JOD</small></strong><span className="flow-footer">{incomeRows.length} حركة <ChevronLeft size={16}/></span></button><button className="flow-card" onClick={()=>onDetails({label:'تفاصيل المصروفات',rows:outRows})}><span className="flow-icon expense"><ArrowUpLeft size={22}/></span><span>إجمالي المصروفات</span><strong dir="ltr">{num(summary.outgoing)} <small>JOD</small></strong><span className="flow-footer">تشمل دفعات الرواتب والسلف <ChevronLeft size={16}/></span></button></section>
 <div className="section-title"><div><h2>النادي بالأرقام</h2><p>حالة الطلاب الحالية، مستقلة عن الفترة المالية</p></div><Users size={20}/></div><section className="student-metrics">{[['الطلاب المسجلون',summary.students],['اشتراكات نشطة',active],['اشتراكات منتهية',expired],['التحقوا هذا الشهر',joined]].map(([label,rows])=><button key={label} onClick={()=>onDetails({label,rows,type:'students'})}><span>{label}</span><strong>{rows.length.toLocaleString('en-US')}</strong><small>عرض القائمة ←</small></button>)}</section>
 <div className="overview-columns"><section className="panel"><div className="panel-heading"><div><h2>آخر الحركات المالية</h2><p>أحدث السجلات ضمن الشهر المختار</p></div>{allowed('finance')&&<button className="quiet" onClick={()=>onNavigate('finance')}>السجل الكامل ←</button>}</div><div className="table"><table><thead><tr><th>البيان</th><th>التاريخ</th><th>المبلغ · JOD</th></tr></thead><tbody>{ledger.slice(0,6).map((r,i)=><tr key={r.id+'_'+i}><td><strong>{r.title||r.studentName||r.reason||'حركة مالية'}</strong><small className="cell-caption">{r.source} · {r.branch}</small></td><td>{dayString(r.date)}</td><td className={'amount '+(r.kind==='income'?'positive':'negative')} dir="ltr">{r.kind==='income'?'+':'−'} {num(r.amount)}</td></tr>)}</tbody></table>{!ledger.length&&<p className="empty">لا توجد حركات خلال الفترة المحددة.</p>}</div></section>
 <div><section className="panel payroll-summary"><div className="panel-heading"><h2>رواتب الشهر</h2><span className="badge">{month}</span></div>{[['earned','المستحق'],['paid','المدفوع'],['remaining','المتبقي']].map(([key,label])=><div className="summary-line" key={key}><span>{label}</span><strong dir="ltr">{num(months.reduce((n,r)=>n+payroll(r)[key],0))} <small>JOD</small></strong></div>)}{allowed('payroll')&&<button className="quiet wide" onClick={()=>onNavigate('payroll')}>إدارة الرواتب والسلف</button>}</section><button className="panel debt-summary" onClick={()=>onDetails({label:'ذمم الطلاب الحالية',rows:debts})}><span>الذمم المتبقية على الطلاب</span><strong dir="ltr">{num(debts.reduce((n,r)=>n+r.amount,0))} <small>JOD</small></strong><small>{debts.length} سجل مستحق · عرض التفاصيل ←</small></button></div></div>
 </>;
}
