import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {Scale,Plus,Search,Star,Target,Users,ArrowRight,X,Printer,Edit3,Trash2} from 'lucide-react';
import {LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,ReferenceLine} from 'recharts';
import {useCollection} from '../../hooks/useCollection';
import {toast} from '../../lib/toast';
import {weightDateMillis,compareWeightStudents} from '../../lib/weightDates';
import {studentAge,trackingGender,automaticCategory,currentTrackingGoal,categoryLabel,kg,birthYear,studentWeightData,measurementDate,displayWeightDate,localDateInput,goalStatus,goalLabel,changeLabel} from '../../lib/weightTracking';
import {printWeightReport} from '../../lib/weightReport';
const field='w-full min-h-11 bg-slate-950 border border-slate-700 rounded-xl px-3 py-2 text-slate-100 focus:outline-none focus:ring-2 focus:ring-yellow-500';
const secondary='min-h-11 px-3 py-2 rounded-xl border border-slate-700 text-slate-300 hover:bg-slate-800 inline-flex items-center justify-center gap-2 text-sm disabled:opacity-40';
const primary='min-h-11 px-4 py-2 rounded-xl bg-yellow-500 text-slate-950 font-bold inline-flex items-center justify-center gap-2 text-sm disabled:opacity-40';
const panel='bg-slate-900 border border-slate-800 rounded-2xl p-4 md:p-5';

function Dialog({title,children,onClose,busy=false}){
 const box=useRef(null),previous=useRef(document.activeElement);
 useEffect(()=>{box.current?.querySelector('input,select,textarea,button')?.focus();return ()=>previous.current?.focus?.();},[]);
 return createPortal(<div className="fixed inset-0 z-[100] bg-black/75 backdrop-blur-sm flex items-center justify-center p-3" dir="rtl"><div ref={box} role="dialog" aria-modal="true" aria-label={title} className="bg-slate-900 border border-slate-700 rounded-2xl shadow-2xl w-full max-w-xl max-h-[90vh] overflow-y-auto p-5" onKeyDown={e=>{
 if(e.key==='Escape'&&!busy){e.stopPropagation();onClose();}
 if(e.key==='Tab'){const nodes=box.current.querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),[tabindex="0"]');const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}
 }}><div className="flex items-center justify-between gap-3 mb-4"><h2 className="text-lg text-slate-100 font-bold">{title}</h2><button disabled={busy} type="button" onClick={onClose} aria-label="إغلاق" className={secondary}><X size={18}/></button></div>{children}</div></div>,document.body);
}
function useSave(onSave,onClose){const [busy,setBusy]=useState(false),[error,setError]=useState('');const guard=useRef(false);const run=async value=>{if(guard.current)return;guard.current=true;setBusy(true);setError('');try{await onSave(value);onClose();}catch(e){setError(e.message||'تعذر الحفظ. حاول مرة أخرى.');}finally{guard.current=false;setBusy(false);}};return {busy,error,run};}
function ErrorText({error}){return error?<p role="alert" className="text-red-300 bg-red-950/30 border border-red-800 rounded-xl p-3 text-sm">{error}</p>:null;}
function MeasureDialog({student,entry,onSave,onClose}){
 const [weight,setWeight]=useState(entry?.weight??''),[note,setNote]=useState(entry?.note||''),[when,setWhen]=useState(localDateInput(entry?measurementDate(entry):new Date()));const {busy,error,run}=useSave(onSave,onClose);
 return <Dialog title={entry?'تعديل القياس':'تسجيل قياس وزن'} onClose={onClose} busy={busy}><p className="text-slate-200 font-bold mb-4">{student.name} <span className="text-slate-400 text-sm">· مواليد {birthYear(student)}</span></p><form className="space-y-4" onSubmit={e=>{e.preventDefault();const ms=Date.parse(when);if(!Number.isFinite(ms)||ms>Date.now()+60000)return toast('اختر تاريخ ووقت قياس صحيحين، وليس في المستقبل.','error');run({weight:Number(weight),note:note.trim(),measuredAt:new Date(ms).toISOString()});}}><label className="block text-sm text-slate-300">الوزن بالكيلوغرام<input className={`${field} mt-2 text-2xl font-bold`} name="weight" type="number" step="0.01" min="0.1" max="300" required value={weight} onChange={e=>setWeight(e.target.value)}/></label><label className="block text-sm text-slate-300">تاريخ القياس والساعة<input className={`${field} mt-2`} type="datetime-local" step="1" required value={when} onChange={e=>setWhen(e.target.value)} dir="ltr"/></label><label className="block text-sm text-slate-300">ملاحظة اختيارية<input className={`${field} mt-2`} placeholder="قبل التدريب، بعد التدريب…" value={note} maxLength={1000} onChange={e=>setNote(e.target.value)}/></label><p className="text-xs text-slate-400">يمكن تسجيل أكثر من قياس باليوم. سيظهر القياس في ملف الطالب وكل مجموعاته.</p><ErrorText error={error}/><button disabled={busy} className={`${primary} w-full`}>{busy?'جارٍ الحفظ…':entry?'حفظ التعديل':'حفظ القياس'}</button></form></Dialog>;
}
function GoalDialog({student,goal,onSave,onClose}){
 const [gender,setGender]=useState(trackingGender(student,goal)),[weight,setWeight]=useState(goal?.weight||''),[direction,setDirection]=useState(goal?.direction||'under');
 const {busy,error,run}=useSave(onSave,onClose),age=studentAge(student),category=automaticCategory(student,gender);
 const categoryId=category?.id||'';
 const valid=gender&&category&&(direction==='over'?Number(weight)===category.over:category.limits.includes(Number(weight)));
 return <Dialog title="الوزن المستهدف" onClose={onClose} busy={busy}>
 <p className="text-slate-200 mb-3">{student.name} · مواليد {birthYear(student)}{age!==null?' · '+age+' سنة':''}</p>
 <p className="text-sm text-slate-400 mb-4">العمر محسوب حسب سنة الميلاد: السنة الحالية ناقص سنة الميلاد.</p>
 {<label className="block text-sm text-slate-300 mb-4">الجنس (يُحفظ للمرة القادمة)<select className={field} value={gender} onChange={e=>{setGender(e.target.value);setWeight('');}}><option value="">حدد الجنس مرة واحدة</option><option value="male">ذكر</option><option value="female">أنثى</option></select></label>}
 <p className="text-slate-100 font-bold mb-4">{category?category.label:age===null?'أكمل تاريخ الميلاد في ملف الطالب':age<6?'لا توجد فئة لهذا العمر في الجدول المرفق':'حدد الجنس لإظهار فئة الطالب'}</p>
 {category&&<><p className="text-sm text-slate-400 mb-3">اختَر الوزن المستهدف</p><div className="flex flex-wrap gap-2 mb-4">{[...category.limits.map(n=>({n,d:'under'})),{n:category.over,d:'over'}].map(({n,d})=><button type="button" key={d+n} onClick={()=>{setWeight(n);setDirection(d);}} aria-pressed={Number(weight)===n&&direction===d} className={Number(weight)===n&&direction===d?primary:secondary}>{d==='under'?'تحت':'فوق'} {n}</button>)}</div>{goal?.weight>0&&!valid&&<p className="text-amber-300 text-sm mb-3">الهدف المحفوظ لا يطابق الفئة الحالية. اختر وزنًا من الفئة الجديدة.</p>}</>}
 <ErrorText error={error}/><div className="flex gap-3 mt-4"><button disabled={busy||!valid} className={primary} onClick={()=>run({categoryId,gender,weight:Number(weight),direction})}>حفظ الوزن المستهدف</button>{goal?.weight>0&&<button disabled={busy} className={secondary} onClick={()=>run({weight:0,categoryId,gender,direction})}>إزالة الهدف</button>}</div>
 </Dialog>;
}
function GroupDialog({group,students,onSave,onClose}){
 const [title,setTitle]=useState(group?.title||''),[kind,setKind]=useState(group?.kind||'tournament'),[date,setDate]=useState(group?.eventDate||''),[ids,setIds]=useState(new Set(group?.studentIds||[])),[search,setSearch]=useState('');const {busy,error,run}=useSave(onSave,onClose);
 return <Dialog title={group?'تعديل المجموعة وطلابها':'بطولة أو مجموعة متابعة'} busy={busy} onClose={onClose}><form className="space-y-4" onSubmit={e=>{e.preventDefault();if(title.trim())run({title:title.trim(),kind,eventDate:date,studentIds:[...ids]});}}><label className="block text-sm text-slate-300">اسم المجموعة<input className={`${field} mt-2`} required value={title} maxLength={120} onChange={e=>setTitle(e.target.value)} placeholder="بطولة الأمل، متابعة الفريق…"/></label><div className="grid grid-cols-2 gap-3"><label className="text-sm text-slate-300">النوع<select className={`${field} mt-2`} value={kind} onChange={e=>setKind(e.target.value)}><option value="tournament">بطولة</option><option value="watchlist">متابعة خاصة</option></select></label><label className="text-sm text-slate-300">التاريخ (اختياري)<input className={`${field} mt-2`} type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div><label className="block text-sm text-slate-300">الطلاب ({students.filter(s=>ids.has(s.id)).length})<input className={`${field} mt-2`} value={search} onChange={e=>setSearch(e.target.value)} placeholder="ابحث بالاسم"/></label><div className="max-h-48 overflow-y-auto space-y-1">{students.filter(s=>String(s.name||'').includes(search.trim())).map(s=><label key={s.id} className="flex items-center gap-3 min-h-11 px-3 rounded-xl bg-slate-950 text-sm text-slate-300"><input type="checkbox" checked={ids.has(s.id)} onChange={()=>setIds(old=>{const next=new Set(old);next.has(s.id)?next.delete(s.id):next.add(s.id);return next;})}/><span>{s.name} · {birthYear(s)}{s._archived?' · مؤرشف':''}</span></label>)}</div><p className="text-xs text-slate-400">إضافة الطالب لأكثر من مجموعة تعرض سجل قياساته نفسه في كل مجموعة.</p><ErrorText error={error}/><button disabled={busy} className={`${primary} w-full`}>{busy?'جارٍ الحفظ…':'حفظ المجموعة'}</button></form></Dialog>;
}

export function WeightsWorkspace({initialStudentId,students=[],archivedStudents=[],selectedBranch,weightsCol,eventsCol,logActivity}){
 const [view,setView]=useState('watch'),[search,setSearch]=useState(''),[selectedId,setSelectedId]=useState(initialStudentId||null),[modal,setModal]=useState(initialStudentId?{type:'measure'}:null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState('');const guard=useRef(false);
 const people=useMemo(()=>students.filter(s=>(!s.branch||s.branch===selectedBranch)&&s.status!=='archived').sort(compareWeightStudents),[students,selectedBranch]);
 const rows=useMemo(()=>weightsCol.data.filter(r=>r.branch===selectedBranch),[weightsCol.data,selectedBranch]);
 const records=useMemo(()=>new Map(people.map(s=>[s.id,studentWeightData(rows,s.id)])),[people,rows]);
 const groups=useMemo(()=>eventsCol.data.filter(g=>g.branch===selectedBranch).sort((a,b)=>String(a.title||'').localeCompare(String(b.title||''),'ar')),[eventsCol.data,selectedBranch]);
 const group=groups.find(g=>g.id===view),selected=people.find(s=>s.id===selectedId),current=records.get(selectedId)||{entries:[],goal:null},goal=selected?currentTrackingGoal(selected,current.goal):current.goal;
 const watched=s=>{const r=records.get(s.id);return r?.goal?.followed!==false&&(r?.goal?.followed===true||r?.entries.length>0||groups.some(g=>g.studentIds?.includes(s.id)));};
 const list=people.filter(s=>(view==='all'||view==='watch'&&watched(s)||group?.studentIds?.includes(s.id))&&[s.name,s.phone,birthYear(s)].some(v=>String(v||'').toLowerCase().includes(search.trim().toLowerCase()))).sort((a,b)=>((weightDateMillis(measurementDate(records.get(b.id)?.entries[0]||{}))||0)-(weightDateMillis(measurementDate(records.get(a.id)?.entries[0]||{}))||0))||String(a.name||'').localeCompare(String(b.name||''),'ar'));
 const filtered=current.entries.filter(r=>{if(!from&&!to)return true;const value=localDateInput(measurementDate(r)).slice(0,10);return value&&(!from||value>=from)&&(!to||value<=to);});
 const dateRangeValid=!from||!to||from<=to;
 const chart=filtered.slice().reverse().map(r=>({...r,time:weightDateMillis(measurementDate(r)),weight:Number(r.weight)})).filter(r=>r.time!==null&&Number.isFinite(r.weight));
 const ready=!weightsCol.loading&&!eventsCol.loading&&!weightsCol.error&&!eventsCol.error;
 useEffect(()=>{setView('watch');setSelectedId(initialStudentId||null);setModal(initialStudentId?{type:'measure'}:null);setFrom('');setTo('');setSearch('');},[selectedBranch,initialStudentId]);
 const checked=async result=>{if(!await result)throw Error('تعذر حفظ التغيير. بقيت البيانات كما هي؛ حاول مرة أخرى.');};
 const log=async(action)=>{try{await logActivity?.(action,selected?.name||'متابعة الأوزان');}catch{/* The saved measurement remains valid even if logging fails. */}};
 const saveGoal=async changes=>{if(!selected)throw Error('اختر الطالب أولاً.');const patch={...changes,updatedAt:new Date().toISOString()};if(current.goal)await checked(weightsCol.update(goal._docId||goal.id,patch));else await checked(weightsCol.add({studentId:selected.id,studentName:selected.name,branch:selectedBranch,_isTarget:true,weight:0,followed:true,createdAt:new Date().toISOString(),...patch}));};
 const saveMeasure=async values=>{if(!selected||!Number.isFinite(values.weight)||values.weight<=0||values.weight>300)throw Error('أدخل وزناً صحيحاً.');if(modal?.entry)await checked(weightsCol.update(modal.entry._docId||modal.entry.id,{...values,updatedAt:new Date().toISOString()}));else await checked(weightsCol.add({...values,studentId:selected.id,studentName:selected.name,branch:selectedBranch,createdAt:new Date().toISOString()}));await log(modal?.entry?'تعديل قياس وزن':'تسجيل قياس وزن');};
 const action=async fn=>{if(guard.current)return;guard.current=true;setBusy(true);setError('');try{await fn();}catch(e){setError(e.message||'تعذر تنفيذ العملية.');}finally{guard.current=false;setBusy(false);}};
 const chooseView=next=>{setView(next);setSelectedId(null);setSearch('');setFrom('');setTo('');};
 const openStudent=id=>{setSelectedId(id);setFrom('');setTo('');setError('');};
 const latest=current.entries[0];
 return <div dir="rtl" className="space-y-5 pb-8"><header className="flex flex-wrap justify-between items-start gap-4"><div><p className="text-xs text-yellow-500 font-bold mb-1">متابعة التدريب والبطولات</p><h1 className="text-2xl md:text-3xl text-slate-100 font-black">متابعة الأوزان</h1><p className="text-sm text-slate-400 mt-2">سجل واحد لكل طالب، أينما تتابعه · {selectedBranch}</p></div><button disabled={!ready} className={secondary} onClick={()=>setModal({type:'group'})}><Plus size={18}/> بطولة / مجموعة متابعة</button></header>
 <div className="flex flex-wrap gap-2"><button className={view==='watch'?primary:secondary} onClick={()=>chooseView('watch')}><Star size={16}/> أتابعهم ({people.filter(watched).length})</button><button className={view==='all'?primary:secondary} onClick={()=>chooseView('all')}><Users size={16}/> جميع الطلاب</button><label className="sr-only" htmlFor="weight-group">البطولات ومجموعات المتابعة</label><select id="weight-group" value={group?view:''} onChange={e=>e.target.value&&chooseView(e.target.value)} className={`${field} !w-auto max-w-full`}><option value="">البطولات ومجموعات المتابعة</option>{groups.map(g=><option key={g.id} value={g.id}>{g.title} ({people.filter(s=>g.studentIds?.includes(s.id)).length})</option>)}</select></div>
 {group&&<div className={`${panel} flex flex-wrap items-center justify-between gap-3`}><div><h2 className="text-slate-100 font-bold">{group.title}</h2><p className="text-xs text-slate-400">{group.kind==='watchlist'?'متابعة خاصة':'بطولة'} {group.eventDate?`· ${group.eventDate}`:''} · جميع قياسات الطالب تظهر هنا</p></div><div className="flex gap-2"><button disabled={!ready||busy} onClick={()=>setModal({type:'group',group})} className={secondary}><Users size={16}/> تعديل وطلاب المجموعة</button><button disabled={!ready||busy} aria-label="حذف المجموعة" className={secondary} onClick={()=>{if(confirm('حذف المجموعة فقط؟ ستبقى أوزان الطلاب محفوظة في ملفاتهم.'))action(async()=>{await checked(eventsCol.remove(group._docId||group.id));chooseView('watch');});}}><Trash2 size={16}/></button></div></div>}
 {!ready&&<p role={weightsCol.error||eventsCol.error?'alert':'status'} className="p-4 rounded-xl bg-slate-900 text-amber-300">{weightsCol.error||eventsCol.error?'تعذر تحميل السجل. تحقق من الاتصال وصلاحية متابعة الأوزان.':'جارٍ تحميل القياسات والمجموعات…'}</p>}<ErrorText error={error}/>
 <div className="grid lg:grid-cols-[340px_minmax(0,1fr)] gap-5 items-start"><aside className={`${panel} ${selected?'hidden lg:block':''}`}><label className="relative block"><span className="sr-only">البحث عن طالب</span><Search size={17} className="absolute right-3 top-3.5 text-slate-500"/><input className={`${field} pr-10`} value={search} onChange={e=>setSearch(e.target.value)} placeholder="اسم الطالب، سنة الميلاد أو الهاتف"/></label><p className="text-xs text-slate-500 my-3">{list.length} طالب · الأحدث قياسًا أولاً</p><div className="max-h-[70vh] overflow-y-auto space-y-2">{list.map(student=>{const r=records.get(student.id),last=r.entries[0],status=goalStatus(last?.weight,r.goal);return <div key={student.id} className={`rounded-xl border p-3 ${selectedId===student.id?'border-yellow-500/50 bg-yellow-500/5':'border-slate-800 bg-slate-950'}`}><button onClick={()=>openStudent(student.id)} className="w-full text-right"><div className="flex items-start justify-between gap-2"><h3 className="font-bold text-slate-100 text-sm break-words">{student.name}</h3><span className="text-xs text-slate-400 shrink-0">{birthYear(student)}</span></div><p className="text-xs text-slate-500 mt-1">{categoryLabel(currentTrackingGoal(student,r.goal).categoryId)}{student._archived?' · مؤرشف':''}</p><div className="flex items-center justify-between mt-3"><strong className="text-xl text-slate-100">{last?`${kg(last.weight)} كغم`:'لا قياسات'}</strong><span className="text-xs text-slate-400">{last?changeLabel(last,r.entries[1]):''}</span></div><p className="text-xs text-slate-400 mt-2">{goalLabel(r.goal)} · {last?status.text:''}</p>{last&&<p className="text-[11px] text-slate-500 mt-1">{displayWeightDate(measurementDate(last))}</p>}</button><button disabled={!ready||busy} className={`${secondary} w-full mt-3`} onClick={()=>{openStudent(student.id);setModal({type:'measure'});}}><Plus size={15}/> قياس جديد</button></div>;})}</div>{!list.length&&ready&&<div className="text-center py-8"><Scale size={28} className="mx-auto text-slate-600 mb-3"/><p className="text-sm text-slate-400">{view==='watch'?'لا يوجد طلاب في متابعتك أو مطابقون للبحث.':'لا يوجد طلاب مطابقون.'}</p>{view!=='all'&&<button className="text-yellow-500 min-h-11 text-sm" onClick={()=>chooseView('all')}>ابحث في جميع الطلاب</button>}</div>}</aside>
 <main className="min-w-0 space-y-4">{!selected?<div className={`${panel} min-h-80 flex flex-col items-center justify-center text-center`}><Scale size={42} className="text-slate-600 mb-4"/><h2 className="text-xl text-slate-200 font-bold">اختَر طالبًا وابدأ المتابعة</h2><p className="text-sm text-slate-400 max-w-md mt-3">ثبّت الطلاب المهمين بنجمة، سجّل القياسات بعد كل تدريب، وتابع التغيّر والهدف من نفس السجل.</p></div>:<>
 <section className={panel}><button className={`${secondary} lg:hidden mb-3`} onClick={()=>setSelectedId(null)}><ArrowRight size={16}/> قائمة الطلاب</button><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-2xl font-bold text-slate-100">{selected.name} <span className="text-base text-slate-400 font-normal">· مواليد {birthYear(selected)}</span></h2><p className="text-sm text-slate-400 mt-2">{categoryLabel(goal?.categoryId)}{selected._archived?' · طالب مؤرشف':''}</p></div><button disabled={!ready||busy} aria-pressed={watched(selected)} className={secondary} onClick={()=>action(()=>saveGoal({followed:!watched(selected)}))}><Star size={17} className={watched(selected)?'fill-yellow-500 text-yellow-500':''}/>{watched(selected)?'ضمن متابعتي':'إضافة للمتابعة'}</button></div><div className="flex flex-wrap gap-2 mt-5"><button disabled={!ready||busy} onClick={()=>setModal({type:'measure'})} className={primary}><Plus size={18}/> تسجيل وزن</button><button disabled={!ready||busy} onClick={()=>setModal({type:'goal'})} className={secondary}><Target size={17}/> الوزن المستهدف</button><button disabled={!ready||!filtered.length||!dateRangeValid} className={secondary} onClick={()=>action(()=>printWeightReport({student:selected,entries:filtered,allEntries:current.entries,goal,branch:selectedBranch,period:from||to?`${from||'البداية'} — ${to||'اليوم'}`:'كامل السجل'}))}><Printer size={17}/> تقرير للأهل / PDF</button></div><div className="grid grid-cols-2 xl:grid-cols-4 gap-3 mt-5">{[['آخر وزن',latest?`${kg(latest.weight)} كغم`:'—',latest?displayWeightDate(measurementDate(latest)):'لم يسجّل قياس بعد'],['عن السابق',latest?changeLabel(latest,current.entries[1]):'—','حسب ترتيب وقت القياس'],['الهدف الحالي',goalLabel(goal),latest?goalStatus(latest.weight,goal).text:'حدد الفئة والهدف'],['سجل الطالب',`${current.entries.length} قياس`,`${groups.filter(g=>g.studentIds?.includes(selected.id)).length} مجموعات`]].map(([label,value,note])=><div key={label} className="bg-slate-950 border border-slate-800 rounded-xl p-3"><p className="text-xs text-slate-400">{label}</p><p className="font-bold text-lg text-slate-100 mt-2">{value}</p><p className="text-[11px] text-slate-500 mt-2">{note}</p></div>)}</div></section>
 <section className={panel}><div className="flex flex-wrap items-end justify-between gap-3"><div><h3 className="font-bold text-slate-100">تطوّر الوزن وسجل القياسات</h3><p className="text-xs text-slate-400 mt-1">الفترة المختارة تنطبق على الرسم والتقرير. المقارنة مع الهدف الحالي.</p></div><div className="flex flex-wrap gap-2 items-end"><label className="text-xs text-slate-400">من<input type="date" value={from} onChange={e=>setFrom(e.target.value)} className={`${field} mt-1`}/></label><label className="text-xs text-slate-400">إلى<input type="date" value={to} onChange={e=>setTo(e.target.value)} className={`${field} mt-1`}/></label>{(from||to)&&<button className={secondary} onClick={()=>{setFrom('');setTo('');}}>كامل السجل</button>}</div></div>{!dateRangeValid?<p role="alert" className="text-amber-300 mt-4">تاريخ البداية يجب أن يسبق النهاية.</p>:<>
 {chart.length>0&&<div dir="ltr" className="mt-6" style={{width:'100%',height:250}}><ResponsiveContainer width="100%" height="100%"><LineChart data={chart} margin={{top:18,right:24,left:0,bottom:12}}><CartesianGrid stroke="#263548" strokeDasharray="3 3"/><XAxis dataKey="time" type="number" domain={([min,max])=>min===max?[min-60000,max+60000]:[min,max]} scale="time" stroke="#8795aa" fontSize={11} tickFormatter={v=>chart[chart.length-1].time-chart[0].time<86400000?new Date(v).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'}):new Date(v).toLocaleDateString('en-GB',{day:'2-digit',month:'2-digit'})}/><YAxis stroke="#8795aa" fontSize={11} domain={['auto','auto']} unit=" kg"/><Tooltip content={({active,payload})=>{if(!active||!payload?.length)return null;const r=payload[0].payload;return <div dir="rtl" className="bg-slate-950 border border-slate-600 rounded-xl p-3 text-slate-100 text-xs"><b>{kg(r.weight)} كغم</b><p className="mt-1">{displayWeightDate(measurementDate(r))}</p><p>{goalStatus(r.weight,goal).text}</p><p className="max-w-60 whitespace-pre-wrap">{r.note}</p></div>;}}/>{Number(goal?.weight)>0&&<ReferenceLine y={Number(goal.weight)} ifOverflow="extendDomain" stroke="#eab308" strokeDasharray="6 4" label={{value:goalLabel(goal),fill:'#eab308',position:'insideTopRight',fontSize:11}}/>}<Line dataKey="weight" type="linear" stroke="#60a5fa" strokeWidth={2.5} dot={{r:4,fill:'#60a5fa'}} activeDot={{r:6}} isAnimationActive={false}/></LineChart></ResponsiveContainer></div>}
 <div className="overflow-x-auto mt-5"><table className="w-full text-sm text-right"><thead><tr className="text-slate-400 text-xs border-b border-slate-700"><th className="py-3 px-2">الوقت والوزن</th><th className="py-3 px-2">عن السابق</th><th className="py-3 px-2">الهدف الحالي</th><th className="py-3 px-2">الملاحظة</th><th className="py-3 px-2"><span className="sr-only">إجراءات</span></th></tr></thead><tbody>{filtered.map(r=>{const index=current.entries.findIndex(e=>e.id===r.id);return <tr key={r.id} className="border-b border-slate-800 align-top"><td className="py-4 px-2"><strong className="text-lg text-slate-100 whitespace-nowrap">{kg(r.weight)} كغم</strong><p className="text-xs text-slate-400 mt-1 min-w-36">{displayWeightDate(measurementDate(r))}</p>{r.updatedAt&&<span className="text-[10px] text-slate-500">معدّل</span>}</td><td className="py-4 px-2 text-slate-300 whitespace-nowrap">{changeLabel(r,current.entries[index+1])}</td><td className="py-4 px-2 text-slate-300 min-w-36">{goalStatus(r.weight,goal).text}</td><td className="py-4 px-2 text-slate-400 whitespace-pre-wrap break-words max-w-64">{r.note||'—'}</td><td className="py-3 px-2"><div className="flex gap-1"><button disabled={!ready||busy} aria-label={`تعديل قياس ${kg(r.weight)}`} className={secondary} onClick={()=>setModal({type:'measure',entry:r})}><Edit3 size={15}/></button><button disabled={!ready||busy} aria-label={`حذف قياس ${kg(r.weight)}`} className={secondary} onClick={()=>{if(confirm('حذف هذا القياس من سجل الطالب؟ سيختفي من جميع المجموعات.'))action(async()=>{await checked(weightsCol.remove(r._docId||r.id));await log('حذف قياس وزن');});}}><Trash2 size={15}/></button></div></td></tr>;})}</tbody></table></div>{!filtered.length&&<p className="text-center text-slate-400 py-8">{current.entries.length?'لا توجد قياسات في الفترة المختارة.':'ابدأ بتسجيل أول قياس للطالب.'}</p>}</>}</section>
 </>}</main></div>
 {modal?.type==='measure'&&selected&&ready&&<MeasureDialog key={selected.id+(modal.entry?.id||'new')} student={selected} entry={modal.entry} onSave={saveMeasure} onClose={()=>setModal(null)}/>}
 {modal?.type==='goal'&&selected&&ready&&<GoalDialog student={selected} goal={goal} onSave={saveGoal} onClose={()=>setModal(null)}/>}
 {modal?.type==='group'&&ready&&<GroupDialog group={modal.group} students={people} onClose={()=>setModal(null)} onSave={async values=>{if(modal.group)await checked(eventsCol.update(modal.group._docId||modal.group.id,values));else {const result=await eventsCol.add({...values,branch:selectedBranch,createdAt:new Date().toISOString()});if(!result)throw Error('تعذر حفظ المجموعة. حاول مرة أخرى.');chooseView(result.id);}}}/>}
 </div>;
}
export default function WeightsManager(props){const weightsCol=useCollection('weights',{where:[['branch','==',props.selectedBranch]]});const eventsCol=useCollection('weight_events',{where:[['branch','==',props.selectedBranch]]});return <WeightsWorkspace {...props} weightsCol={weightsCol} eventsCol={eventsCol}/>;}
