import React,{useEffect,useRef,useState} from 'react';
import {Sun,Moon,ArrowUpLeft,ArrowDown,Menu,X,MapPin,Phone,Clock,CalendarDays,Shield,Trophy,Target,ChevronLeft,MessageCircle,Check,Plus} from 'lucide-react';
import {IMAGES,BRANCHES} from '../lib/constants';
import {useCollection} from '../hooks/useCollection';
import {collection,addDoc} from 'firebase/firestore';
import {db,appId} from '../lib/firebase';
import {formatDate} from '../lib/utils';
import './HomeView.css';
const branches=[{name:BRANCHES.SHAFA,address:'شارع رفعت شموط — بجانب مشاتل ربيع الأردن',phone:'0795629606',map:'https://maps.app.goo.gl/mTqvZD4Ftor3NALJ8?g_st=ic'},{name:BRANCHES.ABU_NSEIR,address:'دوار البحرية — مجمع الفرّا، الطابق الثاني',phone:'0790368603',map:'https://maps.app.goo.gl/yqu6tWBiqrRWGCMJ8?g_st=ic'}];
const nav=[['about','عن الأكاديمية'],['programs','رحلة التدريب'],['schedule','الحصص'],['branches','فروعنا']];
const emptyForm=()=>({name:'',phone:'',dob:'',address:'',branch:BRANCHES.SHAFA});
const wa='https://wa.me/962790368603';
export default function HomeView({setView,schedule=[],scheduleLoading=false,scheduleError=null}){
 const [theme,setTheme]=useState(()=>{try{return localStorage.getItem('brave-home-theme')==='light'?'light':'dark';}catch{return 'dark';}});
 const toggleTheme=()=>setTheme(current=>{const next=current==='dark'?'light':'dark';try{localStorage.setItem('brave-home-theme',next);}catch{}return next;});
 const [menu,setMenu]=useState(false),[selectedBranch,setSelectedBranch]=useState('all'),[showAllNews,setShowAllNews]=useState(false);
 const [register,setRegister]=useState(false),[form,setForm]=useState(emptyForm),[busy,setBusy]=useState(false),[result,setResult]=useState(''),[error,setError]=useState('');
 const dialog=useRef(null),sending=useRef(false),trigger=useRef(null);
 const {data:news=[],loading:newsLoading,error:newsError}=useCollection('news');
 const go=id=>{setMenu(false);document.getElementById('home-'+id)?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});};
 const openRegister=branch=>{trigger.current=document.activeElement;setForm(v=>({...v,branch:branch||v.branch}));setResult('');setError('');setRegister(true);setMenu(false);};
 const closeRegister=()=>{if(!sending.current)setRegister(false);};
 useEffect(()=>{if(!register)return;const el=dialog.current;el.showModal();const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{el.close();document.body.style.overflow=previous;trigger.current?.focus();};},[register]);
 useEffect(()=>{const close=e=>{if(e.key==='Escape')setMenu(false);};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[]);
 const submit=async e=>{e.preventDefault();if(sending.current)return;if(!form.name.trim()||!form.address.trim()){setError('يرجى تعبئة الاسم والعنوان.');return;}sending.current=true;setBusy(true);setError('');try{await addDoc(collection(db,'artifacts',appId,'public','data','registrations'),{...form,name:form.name.trim(),phone:form.phone.trim(),address:form.address.trim(),dob:formatDate(form.dob),date:formatDate(new Date()),status:'new',createdAt:new Date().toISOString()});setResult('وصلنا طلبك بنجاح');setForm(emptyForm());}catch{setError('تعذر إرسال الطلب. حاول مرة أخرى، أو تواصل معنا عبر واتساب.');}finally{sending.current=false;setBusy(false);}};
 const classes=schedule.filter(c=>selectedBranch==='all'||c.branch===selectedBranch||['مشترك','الكل','جميع الفروع'].includes(c.branch));
 const orderedNews=[...news].sort((a,b)=>String(b.createdAt?.toDate?.().toISOString()||b.createdAt||b.date||'').localeCompare(String(a.createdAt?.toDate?.().toISOString()||a.createdAt||a.date||'')));
 return <div className="brave-home" dir="rtl" data-theme={theme}><a className="bh-skip" href="#home-content" onClick={e=>{e.preventDefault();document.getElementById('home-content')?.focus();}}>انتقل إلى المحتوى</a>
 <header className="bh-header"><div className="bh-wrap bh-nav"><button className="bh-brand" onClick={()=>go('top')} aria-label="اكاديمية الشجاع — الرئيسية"><img src={IMAGES.LOGO} alt="" width="48" height="48"/><span><strong>اكاديمية الشجاع</strong><small>BRAVE TAEKWONDO</small></span></button><nav className="bh-desktop-nav" aria-label="التنقل الرئيسي">{nav.map(([id,label])=><button onClick={()=>go(id)} key={id}>{label}</button>)}</nav><div className="bh-nav-actions"><button className="bh-theme-toggle" onClick={toggleTheme} aria-label={theme==='dark'?'تفعيل الوضع الفاتح':'تفعيل الوضع الداكن'} title={theme==='dark'?'الوضع الفاتح':'الوضع الداكن'}>{theme==='dark'?<Sun size={19}/>:<Moon size={19}/>}</button><button className="bh-login" onClick={()=>setView('login')}>تسجيل الدخول <ArrowUpLeft size={16}/></button><button className="bh-menu" aria-label={menu?'إغلاق القائمة':'فتح القائمة'} aria-expanded={menu} aria-controls="bh-mobile-nav" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></div>{menu&&<nav id="bh-mobile-nav" className="bh-mobile-nav" aria-label="قائمة الهاتف">{nav.map(([id,label])=><button key={id} onClick={()=>go(id)}>{label}<ChevronLeft size={16}/></button>)}<button onClick={()=>openRegister()}>طلب تسجيل جديد <Plus size={16}/></button></nav>}</header>
 <main id="home-content" tabIndex={-1}><section id="home-top" className="bh-hero"><div className="bh-wrap bh-hero-grid"><div className="bh-hero-copy"><span className="bh-kicker"><i/> شفا بدران · أبو نصير</span><h1>الشجاعة تبدأ<br/>بخطوة.<br/><em>والخطوة عندك.</em></h1><p>من أول وقفة على البساط إلى كل تحدٍ جديد.<br/>تعلّم التايكواندو، طوّر مهاراتك، وابنِ ثقتك بنفسك مع اكاديمية الشجاع.</p><div className="bh-actions"><button className="bh-primary" onClick={()=>openRegister()}>ابدأ رحلتك معنا <ArrowUpLeft size={21}/></button><button className="bh-text-button" onClick={()=>go('programs')}>اكتشف التدريب <ArrowDown size={17}/></button></div><div className="bh-hero-foot"><span>ثقة بالنفس</span><span>انضباط</span><span>روح رياضية</span></div></div><div className="bh-hero-art" aria-hidden="true"><span className="bh-art-word">BRAVE</span><img src={IMAGES.HERO_BG} alt="" fetchpriority="high"/><span className="bh-art-label">TAEKWONDO<br/>A WAY FORWARD.</span><div className="bh-art-stamp"><ArrowUpLeft size={30}/><span>كل حصة.<br/><b>خطوة أقوى.</b></span></div><span className="bh-art-index">01 — البداية</span></div></div></section>
 <div className="bh-values"><div className="bh-wrap"><span>احترام <Plus/></span><span>إصرار <Plus/></span><span>انضباط <Plus/></span><span>شجاعة <ArrowUpLeft/></span></div></div>
 <section id="home-about" className="bh-section bh-light"><div className="bh-wrap"><div className="bh-section-heading"><div><span className="bh-eyebrow">01 / أكثر من رياضة</span><h2>قوة على البساط.<br/><span>ثقة في الحياة.</span></h2></div><p>في اكاديمية الشجاع، رحلة التدريب تبدأ بالتعلّم وتكبر بالالتزام. مساحة للحركة، لتطوير المهارات، ولتعلّم قيمة المحاولة من جديد.</p></div><div className="bh-benefits">{[[Shield,'الاحترام أولًا','روح رياضية وانضباط يرافقان الطالب داخل التدريب وخارجه.'],[Target,'التقدّم خطوة بخطوة','من الأساسيات إلى مهارات أكثر تقدّمًا، كل مرحلة تبني على التي قبلها.'],[Trophy,'هدف يدفعك للأمام','تعلّم، تمرّن، وواجه تحديات جديدة مع تطوّر مستواك.']].map(([Icon,title,text],i)=><article key={title}><div className="bh-benefit-top"><Icon size={28} strokeWidth={1.5}/><small>0{i+1}</small></div><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
 <section id="home-programs" className="bh-section bh-programs"><div className="bh-wrap"><div className="bh-section-heading"><div><span className="bh-eyebrow">02 / رحلة التدريب</span><h2>لكل بداية،<br/>مسار يستحق.</h2></div><p>سواء كنت تبدأ اليوم أو تكمل مشوارك،<br/>تواصل معنا لاختيار المجموعة المناسبة لمستواك.</p></div><div className="bh-program-grid">{[['01','الخطوة الأولى','تأسيس ومبتدئون','تعلّم الوقفات والحركات الأساسية، وتعرّف على التايكواندو خطوة بخطوة.','البداية من هنا'],['02','تطوّر كل يوم','الأحزمة الملوّنة','واصل بناء مهاراتك، وطوّر التوازن والتركيز والتحكم في الحركة.','كمّل مشوارك'],['03','تحدٍّ أكبر','المستويات المتقدّمة','تدريب على مهارات أكثر تقدّمًا، مع التركيز على الأداء والانضباط.','ارفع مستواك']].map(([n,tag,title,text,cta])=><article key={n}><div className="bh-program-number">{n}</div><span className="bh-program-tag">{tag}</span><h3>{title}</h3><p>{text}</p><button onClick={()=>openRegister()}>{cta}<ArrowUpLeft size={22}/></button></article>)}</div></div></section>
 <section id="home-schedule" className="bh-section bh-light"><div className="bh-wrap"><div className="bh-section-heading"><div><span className="bh-eyebrow">03 / وقتك على البساط</span><h2>رتّب أسبوعك.<br/><span>خلّي للتدريب وقت.</span></h2></div><a className="bh-outline-link" href={wa} target="_blank" rel="noreferrer">ساعدني أختار الحصة <MessageCircle size={18}/></a></div><div className="bh-filter" role="group" aria-label="تصفية الحصص حسب الفرع">{['all',BRANCHES.SHAFA,BRANCHES.ABU_NSEIR].map(b=><button key={b} aria-pressed={b===selectedBranch} onClick={()=>setSelectedBranch(b)}>{b==='all'?'جميع الفروع':b}</button>)}</div><div className="bh-schedule-list">{scheduleLoading?<p className="bh-empty" role="status">جارٍ تحميل مواعيد الحصص…</p>:scheduleError?<p className="bh-empty">تعذر تحميل المواعيد الآن. تواصل معنا لتأكيد موعد الحصة.</p>:classes.length?classes.map((c,i)=><article key={c.id||i}><span className="bh-class-index">{String(i+1).padStart(2,'0')}</span><div className="bh-class-title"><small>{c.branch}</small><h3>{c.level}</h3></div><span><CalendarDays size={17}/>{Array.isArray(c.days)?c.days.join(' / '):c.days}</span><span><Clock size={17}/><b>{c.time}</b></span><button aria-label={'طلب الانضمام إلى '+c.level} onClick={()=>openRegister(branches.some(b=>b.name===c.branch)?c.branch:undefined)}><ArrowUpLeft size={23}/></button></article>):<p className="bh-empty">لا توجد حصص منشورة لهذا الفرع حاليًا. تواصل معنا لمعرفة المواعيد.</p>}</div></div></section>
 <section id="home-branches" className="bh-section bh-branches"><div className="bh-wrap"><div className="bh-section-heading"><div><span className="bh-eyebrow">04 / قريبين منك</span><h2>نفس الروح.<br/>في فرعين.</h2></div><p>اختر الفرع الأقرب، وخلّي الخطوة الأولى أسهل.<br/>الموقع والتواصل، كلّهم في مكان واحد.</p></div><div className="bh-branch-grid">{branches.map((b,i)=><article key={b.name}><div className={'bh-branch-visual bh-branch-'+i}>{i===1?<img src={IMAGES.BRANCH_ABU_NSEIR} loading="lazy" alt="واجهة فرع أبو نصير"/>:<><img src={IMAGES.BRANCH_SHAFA} loading="lazy" alt="شعار اكاديمية الشجاع"/><span>من هنا تبدأ الحكاية</span></>}<b>{b.name}{b.name===BRANCHES.ABU_NSEIR?' / الفرع الرئيسي':''}</b></div><div className="bh-branch-info"><h3>{b.name}</h3><p><MapPin size={17}/>{b.address}</p><div><a href={b.map} target="_blank" rel="noreferrer">افتح الموقع <ArrowUpLeft size={18}/></a><a href={'tel:'+b.phone} aria-label={'اتصل بفرع '+b.name}><Phone size={16}/><span dir="ltr">{b.phone}</span></a></div><button onClick={()=>openRegister(b.name)}>سجّل في هذا الفرع <ChevronLeft size={16}/></button></div></article>)}</div></div></section>
 <section id="home-news" className="bh-section bh-light"><div className="bh-wrap"><div className="bh-section-heading"><div><span className="bh-eyebrow">05 / من الأكاديمية</span><h2>آخر الأخبار<br/><span>والعروض.</span></h2></div>{orderedNews.length>3&&<button className="bh-outline-link" onClick={()=>setShowAllNews(!showAllNews)}>{showAllNews?'عرض أقل':'كل الأخبار'}<ArrowUpLeft size={18}/></button>}</div>{newsLoading?<p className="bh-empty">جارٍ تحميل الأخبار…</p>:newsError?<p className="bh-empty">الأخبار غير متاحة الآن. تابعنا لاحقًا أو تواصل معنا.</p>:!orderedNews.length?<div className="bh-empty">أخبارنا الجديدة ستظهر هنا. للاستفسار عن التسجيل والعروض، <a href={wa} target="_blank" rel="noreferrer">تواصل معنا</a>.</div>:<div className="bh-news-grid">{(showAllNews?orderedNews:orderedNews.slice(0,3)).map((n,i)=><article key={n.id||i}>{n.image?<img src={n.image} alt={n.title||'خبر من الأكاديمية'} loading="lazy"/>:<div className="bh-news-art" aria-hidden="true"><Trophy size={44}/><span>BRAVE / NEWS</span></div>}<div><small>{n.branch||'أخبار الأكاديمية'}</small><h3>{n.title}</h3><p>{n.desc}</p></div></article>)}</div>}</div></section>
 <section className="bh-section bh-faq"><div className="bh-wrap bh-faq-grid"><div><span className="bh-eyebrow">قبل أول حصة</span><h2>أسئلة بسيطة.<br/>بداية أوضح.</h2><p>عندك سؤال ثاني؟ إحنا معك.</p><a href={wa} target="_blank" rel="noreferrer">اسألنا على واتساب <ArrowUpLeft size={20}/></a></div><div>{[['كيف أسجّل في الأكاديمية؟','عبّئ طلب التسجيل من الموقع وحدّد الفرع. فريق الأكاديمية يتواصل معك لاستكمال التفاصيل وتأكيد المجموعة المناسبة.'],['كيف أعرف المجموعة المناسبة؟','تواصل معنا واذكر عمر الطالب وخبرته السابقة، لنساعدك في اختيار المجموعة والموعد المناسبين.'],['وين بلاقي مواعيد التدريب؟','المواعيد المنشورة موجودة في قسم الحصص، ويمكنك عرضها حسب الفرع. لتأكيد الموعد قبل الزيارة تواصل مع الفرع مباشرة.'],['أنا طالب مسجّل، كيف أدخل حسابي؟','اضغط تسجيل الدخول أعلى الصفحة، ثم اختر الطالب أو ولي الأمر وادخل ببيانات حسابك.']].map(([q,a])=><details key={q}><summary>{q}<Plus size={20}/></summary><p>{a}</p></details>)}</div></div></section>
 <section className="bh-final"><div className="bh-wrap"><span className="bh-eyebrow">خطوتك القادمة</span><h2>لا تنتظر الشجاعة.<br/>ابدأ، <span>وابنِها.</span></h2><div className="bh-actions"><button className="bh-primary" onClick={()=>openRegister()}>قدّم طلب تسجيل <ArrowUpLeft size={22}/></button><a href={wa} target="_blank" rel="noreferrer">احكي معنا أولًا <MessageCircle size={20}/></a></div></div><span className="bh-final-word" aria-hidden="true">BRAVE</span></section>
 </main><footer className="bh-footer"><div className="bh-wrap"><div className="bh-footer-top"><div className="bh-brand"><img src={IMAGES.LOGO} alt="شعار الأكاديمية" loading="lazy"/><span><strong>اكاديمية الشجاع</strong><small>BRAVE TAEKWONDO</small></span></div><div>{nav.map(([id,label])=><button key={id} onClick={()=>go(id)}>{label}</button>)}</div><a href="tel:+962790368603" dir="ltr" aria-label="اتصل بالفرع الرئيسي أبو نصير">+962 7 9036 8603</a></div><div className="bh-footer-bottom"><span>© {new Date().getFullYear()} اكاديمية الشجاع. جميع الحقوق محفوظة.</span><button onClick={()=>setView('login')}>بوابة الطالب · المدرب · الإدارة <ArrowUpLeft size={14}/></button></div></div></footer>
 <a className="bh-whatsapp" href={wa} target="_blank" rel="noreferrer" aria-label="تواصل معنا عبر واتساب"><MessageCircle size={25}/></a>
 {register&&<dialog ref={dialog} className="bh-dialog" aria-labelledby="bh-register-title" onCancel={e=>{e.preventDefault();closeRegister();}} onClick={e=>{if(e.target===e.currentTarget)closeRegister();}}><div className="bh-dialog-inner"><button className="bh-dialog-close" aria-label="إغلاق طلب التسجيل" onClick={closeRegister} disabled={busy}><X/></button>{result?<div className="bh-confirmation" role="status"><Check size={44}/><h2 id="bh-register-title">{result}</h2><p>فريق الأكاديمية رح يتواصل معك لاستكمال التفاصيل. نتطلع نشوفك على البساط.</p><button className="bh-primary" onClick={closeRegister}>العودة للموقع</button></div>:<><span className="bh-eyebrow">أول خطوة تبدأ هون</span><h2 id="bh-register-title">انضم للشجاع.</h2><p>أرسل بيانات الطالب وسنتواصل معك لتأكيد التفاصيل.</p><form onSubmit={submit}><fieldset disabled={busy}><label>اسم الطالب الرباعي<input autoFocus required maxLength={120} autoComplete="name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="الاسم الكامل"/></label><div className="bh-form-row"><label>رقم ولي الأمر<input type="tel" required autoComplete="tel" maxLength={20} pattern="[+0-9٠-٩ ]{9,20}" dir="ltr" placeholder="079xxxxxxx" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>تاريخ ميلاد الطالب<input type="date" lang="en" required max={new Date().toLocaleDateString('en-CA')} value={form.dob} onChange={e=>setForm({...form,dob:e.target.value})}/></label></div><label>العنوان<input required maxLength={200} autoComplete="street-address" placeholder="المنطقة — الشارع" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><label>الفرع<select value={form.branch} onChange={e=>setForm({...form,branch:e.target.value})}>{branches.map(b=><option key={b.name}>{b.name}</option>)}</select></label></fieldset>{error&&<p className="bh-form-error" role="alert">{error}</p>}<button type="submit" className="bh-primary" disabled={busy}>{busy?'جارٍ إرسال الطلب…':'إرسال طلب التسجيل'}<ArrowUpLeft size={20}/></button><small>إرسال الطلب هو الخطوة الأولى، ويُستكمل التسجيل بالتواصل مع الأكاديمية.</small></form></>}</div></dialog>}
 </div>;
}
