import React,{useState,useRef,useEffect} from 'react';
import {ArrowUpLeft,ArrowRight,User,Users,Lock,ShieldCheck,Eye,EyeOff,Sun,Moon,X,MessageCircle,Check,Loader2} from 'lucide-react';
import {IMAGES} from '../lib/constants';
import {collection,addDoc,serverTimestamp} from 'firebase/firestore';
import {db,appId} from '../lib/firebase';
import './LoginView.css';
const portals=[{id:'student',label:'طالب / ولي أمر',icon:User,title:'كل خطوة، أقرب لهدفك.',description:'تابع ملف الطالب، الحضور، الاشتراك وآخر مستجداته من مكان واحد.',features:['ملف الطالب','متابعة الحضور','الاشتراكات']},{id:'coach',label:'المدرب',icon:Users,title:'معك في كل حصة.',description:'ادخل إلى أدوات النادي وصفحات الطلاب المتاحة لحسابك.',features:['إدارة الطلاب','متابعة التدريب','أدوات النادي']},{id:'management',label:'الإدارة',icon:ShieldCheck,title:'رؤية أوضح. إدارة أفضل.',description:'تابع شؤون النادي المالية، المدربين والتقارير حسب صلاحيات حسابك.',features:['حسابات النادي','فريق التدريب','التقارير']}];
export default function LoginView({setView,handleLogin,loginError,setLoginError}){
 const [portal,setPortal]=useState('student'),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[showPassword,setShowPassword]=useState(false),[busy,setBusy]=useState(false),[localError,setLocalError]=useState(''),[caps,setCaps]=useState(false);
 const [theme,setTheme]=useState(()=>{try{return localStorage.getItem('brave-home-theme')==='light'?'light':'dark';}catch{return 'dark';}});
 const [forgot,setForgot]=useState(false),[recovery,setRecovery]=useState({studentName:'',phone:''}),[recovering,setRecovering]=useState(false),[recoveryError,setRecoveryError]=useState(''),[sent,setSent]=useState(false);
 const lock=useRef(false),recoveryLock=useRef(false),dialog=useRef(null),opener=useRef(null);
 const selected=portals.find(p=>p.id===portal),Icon=selected.icon;
 const clearError=()=>{setLoginError?.('');setLocalError('');};
 const toggleTheme=()=>setTheme(v=>{const next=v==='dark'?'light':'dark';try{localStorage.setItem('brave-home-theme',next);}catch{}return next;});
 const submit=async e=>{e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setLocalError('');try{await handleLogin(username.trim(),password,portal);}catch{setLocalError('تعذر تسجيل الدخول الآن. تحقق من الاتصال وحاول مرة أخرى.');}finally{lock.current=false;setBusy(false);}};
 const closeRecovery=()=>{if(!recoveryLock.current)setForgot(false);};
 useEffect(()=>{if(!forgot)return;const node=dialog.current;node.showModal();const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{node.close();document.body.style.overflow=old;opener.current?.focus();};},[forgot]);
 const recover=async e=>{e.preventDefault();if(recoveryLock.current)return;const name=recovery.studentName.trim();const phone=recovery.phone.replace(/[٠-٩]/g,n=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(n))).replace(/\D/g,'');if(!name||phone.length!==10){setRecoveryError('أدخل الاسم ورقم هاتف من 10 أرقام.');return;}recoveryLock.current=true;setRecovering(true);setRecoveryError('');try{await addDoc(collection(db,'artifacts',appId,'public','data','password_reset_requests'),{studentName:name,phone,status:'new',createdAt:serverTimestamp()});setSent(true);setRecovery({studentName:'',phone:''});}catch{setRecoveryError('تعذر إرسال الطلب. حاول مرة أخرى أو تواصل مع الأكاديمية.');}finally{recoveryLock.current=false;setRecovering(false);}};
 return <div className="brave-login" data-theme={theme} dir="rtl"><header className="bl-header"><button className="bl-brand" onClick={()=>setView('home')} disabled={busy}><img src={IMAGES.LOGO} alt=""/><span><strong>اكاديمية الشجاع</strong><small>BRAVE TAEKWONDO</small></span></button><div><button className="bl-theme" onClick={toggleTheme} aria-label={theme==='dark'?'تفعيل الوضع الفاتح':'تفعيل الوضع الداكن'}>{theme==='dark'?<Sun size={19}/>:<Moon size={19}/>}</button><button className="bl-home" onClick={()=>setView('home')} disabled={busy}>الرئيسية <ArrowUpLeft size={17}/></button></div></header>
 <main className="bl-layout"><section className="bl-intro"><span className="bl-eyebrow"><i/> مساحة أعضاء الأكاديمية</span><h1>شجاعتك على البساط.<br/><em>ومشوارك هون.</em></h1><p>بوابتك لكل ما يخص رحلتك مع الشجاع.<br/>اختر حسابك، وكمّل من مكان ما وصلت.</p><div className="bl-art" aria-hidden="true"><img src={IMAGES.HERO_BG} alt=""/><span>BRAVE</span><b>خطوة اليوم.<br/>قوة بكرة.</b><small>TAEKWONDO / A WAY FORWARD</small></div><div className="bl-intro-footer"><span>شفا بدران · أبو نصير</span><span>اكاديمية الشجاع</span></div></section>
 <section className="bl-card" aria-labelledby="bl-title"><div className="bl-card-heading"><span className="bl-eyebrow">أهلًا برجعتك</span><h2 id="bl-title">تسجيل الدخول</h2><p>اختر واجهتك وأدخل بيانات حسابك.</p></div><form onSubmit={submit} aria-busy={busy}><fieldset className="bl-portals" disabled={busy}><legend>الدخول بصفة</legend><div>{portals.map(p=><label key={p.id} className={portal===p.id?'selected':''}><input type="radio" name="portal" value={p.id} checked={portal===p.id} onChange={()=>{setPortal(p.id);clearError();setShowPassword(false);}}/><p.icon size={22} strokeWidth={1.6}/><span>{p.label}</span>{portal===p.id&&<Check className="bl-selected-check" size={11}/>}</label>)}</div></fieldset><div className="bl-context" aria-live="polite"><Icon size={18}/><div><strong>{selected.title}</strong><p>{selected.description}</p></div></div>
 <div className="bl-field"><label htmlFor="bl-username">اسم المستخدم أو البريد الإلكتروني</label><div><User size={18}/><input id="bl-username" required autoComplete="username" autoCapitalize="none" spellCheck={false} dir="auto" placeholder="أدخل اسم المستخدم" value={username} disabled={busy} onChange={e=>{setUsername(e.target.value);clearError();}}/></div></div>
 <div className="bl-field"><label htmlFor="bl-password">كلمة المرور</label><div><Lock size={18}/><input id="bl-password" required autoComplete="current-password" type={showPassword?'text':'password'} dir="auto" placeholder="أدخل كلمة المرور" disabled={busy} value={password} onChange={e=>{setPassword(e.target.value);clearError();}} onKeyUp={e=>setCaps(e.getModifierState('CapsLock'))} onBlur={()=>setCaps(false)}/><button className="bl-eye" type="button" disabled={busy} onClick={()=>setShowPassword(!showPassword)} aria-label={showPassword?'إخفاء كلمة المرور':'إظهار كلمة المرور'} aria-pressed={showPassword}>{showPassword?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></div>{caps&&<p className="bl-caps">زر Caps Lock مفعّل.</p>}
 <div className="bl-help-row"><span>استخدم بيانات حسابك المسجّل</span><button type="button" disabled={busy} onClick={()=>{opener.current=document.activeElement;setSent(false);setRecoveryError('');setForgot(true);}}>نسيت بيانات الدخول؟</button></div>{(localError||loginError)&&<p className="bl-error" role="alert">{localError||loginError}</p>}<button className="bl-submit" disabled={busy} type="submit">{busy?<><Loader2 className="bl-spin" size={18}/>جارٍ التحقق…</>:<>دخول {portal==='student'?'بوابة الطالب':portal==='coach'?'بوابة المدرب':'الإدارة العامة'}<ArrowUpLeft size={20}/></>}</button></form><div className="bl-card-footer"><span>تحتاج مساعدة بالدخول؟</span><a href="https://wa.me/962790368603" target="_blank" rel="noreferrer">تواصل مع الأكاديمية <MessageCircle size={16}/></a></div></section></main>
 <footer className="bl-footer"><span>© {new Date().getFullYear()} اكاديمية الشجاع</span><span>مساحة واحدة. كل خطواتك.</span></footer>
 {forgot&&<dialog ref={dialog} className="bl-dialog" aria-labelledby="bl-recovery-title" onCancel={e=>{e.preventDefault();closeRecovery();}} onClick={e=>{if(e.target===e.currentTarget)closeRecovery();}}><button className="bl-close" aria-label="إغلاق المساعدة" disabled={recovering} onClick={closeRecovery}><X size={21}/></button>{sent?<div className="bl-success" role="status"><Check size={34}/><h2 id="bl-recovery-title">وصلنا طلبك</h2><p>ستتواصل معك الإدارة بعد التحقق من بيانات الطالب.</p><button className="bl-submit" onClick={closeRecovery}>تمام، رجوع للدخول <ArrowRight size={18}/></button></div>:<><span className="bl-eyebrow">نساعدك ترجع لحسابك</span><h2 id="bl-recovery-title">استعادة بيانات الدخول</h2>{portal==='student'?<><p>أدخل اسم الطالب ورقم الهاتف المسجّل ليراجع فريق الأكاديمية طلبك.</p><form onSubmit={recover}><div className="bl-field"><label htmlFor="bl-recovery-name">اسم الطالب الرباعي</label><div><input id="bl-recovery-name" required autoComplete="name" maxLength={120} disabled={recovering} value={recovery.studentName} onChange={e=>setRecovery({...recovery,studentName:e.target.value})}/></div></div><div className="bl-field"><label htmlFor="bl-recovery-phone">رقم الهاتف المسجّل</label><div><input id="bl-recovery-phone" required type="tel" autoComplete="tel" dir="ltr" placeholder="079xxxxxxx" pattern="[0-9٠-٩]{10}" maxLength={10} disabled={recovering} value={recovery.phone} onChange={e=>setRecovery({...recovery,phone:e.target.value})}/></div></div>{recoveryError&&<p className="bl-error" role="alert">{recoveryError}</p>}<button className="bl-submit" disabled={recovering}>{recovering?'جارٍ إرسال الطلب…':'إرسال طلب للإدارة'}<ArrowUpLeft size={18}/></button></form></>:<><p>لاستعادة حساب {portal==='coach'?'المدرب':'الإدارة'}، تواصل مع مدير الأكاديمية للتحقق من حسابك ومساعدتك بالدخول.</p><a className="bl-submit" href="https://wa.me/962790368603" target="_blank" rel="noreferrer">تواصل مع الأكاديمية <MessageCircle size={18}/></a></>}</>}</dialog>}
 </div>;
}
